### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#10]
This issue will cover progress and discussion for the reading progress bar feature.

**Comment by KianBadie** [comment]
@coiko I have implemented an initial version of the progress bar. I attached a gif as well as an image since the gif seems to alter the shadows of the progress bar a bit. I tried to combine the ideas of the mocks that you created with the single color design and horizontal chapter markers from our discussion. When the image is non-full screen, it may appear that the chapter markers are just black lines, but they actually have a white fill. What are your thoughts? Is there anything you would like to change?

I also have a couple questions about the progress bar that I was wondering about:
- Should we add an option to hide the progress bar? I was reading online on opinions about progress bars, and some people liked it and some people preferred it to not show. Would giving the options be the best of both worlds? What do you think?
- Should chapter markers be equal distanced from each other? The way I made it, the spacing in between the markers is reflective of the chapter length.
- Should the [introduction landing page](https://www.cellstructureatlas.org/begin.html) or the appendix pages be included in this? I currently excluded them from it, so there is no progress bar showing on those pages.
## Image
![progress-bar](https://user-images.githubusercontent.com/18221058/118050964-13b1f380-b335-11eb-8c0e-0333bf41d480.PNG)
## Gif
![progress-bar](https://user-images.githubusercontent.com/18221058/118050978-17457a80-b335-11eb-9cda-952c9291682e.gif)

**Comment by KianBadie** [comment]
@coiko Also, here are some mocks of simple pop up menu styling options. The first set of black with a white border is almost identical to Amazon's Cloud Reader pop up menu for their progress bar. I left the message blank to leave room for whatever message and to focus on the look of the menu. It's also almost identical to Amazon's Cloud Reader wording to denote progress, but a simple message could be something like "9.24% Page 11 of 119".

Lastly, I had an idea for the chapter markers. If you wanted to bring back some of the nice touches of color that you made in your mocks, maybe the chapter markers could be the colors of the chapter themes.

**Comment by coiko** [comment]
@KianBadie Sorry for the late response, but this is fantastic!  I love it!  And I think the fill/stroke is perfect.  To answer your questions:

- Yes, it sounds like a good idea to add a hide option.  What about a small icon at the bottom right (maybe a partially-filled lozenge) that could be selected/deselected to show/hide the bar?  We could have a hover-over explanation of something like "show/hide progress bar"
- I like the way you did it with the chapters being unequal lengths - it's visually fun and more accurate about how long the book will take to go through
- Yes, I agree that we should exclude the Introduction, Outlook, and Appendix sections.  I like it just the way you did it with the 10 main chapters

And I like the idea of the colored chapter markers!  It could be a subtle bit of theme fun.  Although I also like how clean your design here is.  So I guess it's up to you if you want to try it out with the risk that we might like it better the way it is now.  (If you don't want to, I'm totally fine with leaving it as is.)

I don't see the mocks for the pop up menu styling - can you link them again?

**Comment by KianBadie** [comment]
@coiko No problem! 
- Awesome! When you say bottom right, is this in context of the nav menu or the footer? And my apologies, I'm not familiar with what a lozenge is. I tried googling for some examples but I'm not sure if it is the same idea that you are describing. Is it a diamond shape?
- I'll keep it as is then!
- Sounds good, I will exclude them from the progress bar and hide the progress bar on those pages.

I'll try it out and post some screenshots to see how they look. And yes my apologies, I forgot to attach the actual link for the mocks. Here they are: https://www.figma.com/proto/VzbV4r4OdcU6vUiViP0MO4/Progress-Bar?node-id=3%3A0&scaling=min-zoom&page-id=0%3A1

**Comment by coiko** [comment]
@KianBadie Yeah, that was confusing, sorry!  I was thinking of something like [this](https://thenounproject.com/term/progress-bar/3318844/) or [this](https://thenounproject.com/term/progress-bar/3318904/).  What do you think?

As for placement, I was thinking the bottom right of the main window, just above the footer (or the progress bar if it's shown).

The mocks looks fantastic!  I think my favorite is actually the first one (Amazon must know what they're doing).  As for a message, I like the idea of keeping it simple, with just a percentage (I might round to a whole number) and a page count.  Thanks!

**Comment by KianBadie** [comment]
@coiko No worries! I see what you are saying now. So that icon in the bottom right of the main window could be clicked on or off to show the progress bar. Do you have any preference on the icons? I think the second one you linked (that was split into quarters) was nice and clear.

 Yes, I think the first one looks great too. After the first one, I was having trouble coming up with other options that would look as good. And sounds good! So something like "9% Page 11"? Or would you want a total page count as well? And just to throw the option out there, they can be on a single line or multiline.

**Comment by coiko** [comment]
@KianBadie Thanks!  That sounds great.  Maybe it could be right at the end of the progress bar, so it's almost like the bar shelves/unshelves from it?  And yes, I like the second link, too.  It's a better match for your neat design.  We might also want to recolor it to match the grey theme.

I like the idea of splitting the hover message into two lines, maybe with the percentage on top and the page 11 of 119 (I liked the way you gave the total, too) on the bottom.  I think that will look great!

**Comment by KianBadie** [comment]
@coiko I see, so the progress bar would not be full width and it would leave space for that toggle button? If so, would the button be floating? Kind of like the arrow navigation we have now. Or would it be attached to the bottom right of the page? Like the video/image slider tabs?

Everything else sounds good to me!

**Comment by KianBadie** [comment]
@coiko I just added the progress bar changes, so it should be available on our testing site shortly after this message. It only appears on non mobile sized screens (I assumed it was ok to leave that out for now). It also has the grace period functionality that adds some buffer time before the pop up auto closing. I decided to merge the changes now, because I figured adding the pop up menu for chapter markers and the progress bar shelving button will take longer than today and the progress bar was already in a mergeable state. The only issue that I can think of is the overlap that happens between the progress bar and the page elements on long and short screens. I am still figuring out how to fix without changing the positioning of the video/text elements too much, but I also assumed it was not common enough to prevent the merge. I'll try to have that sorted out next week, hopefully along with the text shelving button and chapter marker pop ups.

Going back to mobile, do you feel fitting that the progress bar does not display on mobile? I think the pop up menu might be not as intuitive to access. I can't think of another way of opening it besides tapping. However, it might still be nice visually to see the progress on mobile.

**Comment by KianBadie** [comment]
@coiko [Here](https://www.figma.com/proto/VzbV4r4OdcU6vUiViP0MO4/Progress-Bar?node-id=18%3A3&scaling=min-zoom&page-id=18%3A2) are some mocks for a shelving button for the progress bar. The first 3 examples are along the lines of what we discussed today. I keep feeling like I want something to change about them, but I can not put my finger on it. What are your thoughts on the first 3? I think a constraint to keep in mind is the icon we use for the progress bar. Since we can't control the shape of it, the dimensions of the progress bar icon are locked. So if we make the button shorter or longer, the dimensions will stay consistent.

The examples after are a different take. The 4th examples is a toggle in the nav menu. The 5th example is a floating button in the bottom right of the footer. And the 6th examples is a toggle in the bottom right of the footer.

For all of these, the fonts, colors, or wording might be off a bit. But we can always change those!

**Comment by coiko** [comment]
@KianBadie Sorry for the late response!  (I was letting this mentally percolate and got carried away.)  First off, thanks for getting this onto the testing site!  It's super cool to see it, and I love the styling!

My initial thoughts from playing with it are that it might be better to have the status pop-up only appear when you hover over the current place indicator, not the whole bar.  Otherwise, it can get distracting when you put your cursor in the footer.  (This might be a personal quirk, but when I'm reading/watching something, I tend to stash the cursor at the bottom of the page so it doesn't cover anything.)  The grace period for the hover also felt a little long to me, especially when I was triggering the popup accidentally as just described.  Since you have the great behavior that it detects when you're hovering over the popup and leaves it open, it might be good to shorten that grace period.  I'd also (as usual) make the font in the popup smaller so it's not so visually dominant on the page - maybe on the same scale as the citation metadata.  That might help with the element overlap on short screens, too.  (Which, in general, I don't think is a problem, since the popup appears in front, which feels natural.)

As for the shelving option, I have to apologize for leading you down the wrong road.  I think the icon is problematic and instead, I love the toggle (which I think was your initial idea - sorry!).  I think the last mock you made, with the toggle at the bottom right is perfect!  I like it better there than in the Nav menu, where it might be less intuitive for someone to find it.  What do you think about moving the other footer elements horizontally so they're all evenly spaced?  I think it could look cool, especially with the alternating all-caps text.  The only thing about the toggle I think we might be able to improve is the background color that denotes the selection.  If the dark blue-green doesn't give enough contrast with the footer, how about using a light grey instead?

**Comment by KianBadie** [comment]
@coiko No worries at all! 

I see what you are saying. I would be happy to change the pop up to only show when hovering the current place marker. Tweaking the grace period will also be very easy. It is currently at 1s, how does 0.5s sound? I will go ahead and decrease the font to be similar to the citation font. I'm also glad the overlap wasn't too bad!

No worries again! I think making all the footer elements evenly spaced could work out! When you say alternating all-caps text, is that in reference to how the "Progress" in not in all caps like the other footer element, or is there a styling I should add? Yeah I think light grey could work. I will also try some shade of blue/green to see if they make cut!

**Comment by coiko** [comment]
Thanks @KianBadie!  0.5s sounds perfect.  And don't change any of the styling for the "Progress" - it's perfect.  I was just saying (incoherently) that I think it will look nice with the two all-caps elements that are links (the Library and the About) alternating with the two softer elements (the copyright and the Progress toggle).

**Comment by KianBadie** [comment]
@coiko Ah I see! I will go ahead and start implementing those and show you as soon as there is something concrete!

**Comment by KianBadie** [comment]
@coiko The progress bar shelfing/un-shelfing option is almost there. There is only one glaring thing that I'm not sure how to alleviate. In the second gif, you can see that on the page load, the progress bar switch transitions on. This is because the default is off, and the page realized that on the last page it was on, so it turns on. Unfortunately, even with the transition off, the result is similar with the difference of before/after being visible on page load (just without the transition). One thing I tried was turning off the white knob of the switch until the transition is made. However, the bottom line of the result was that there is a visible before and after state on the page load. So there would be no knob for maybe a quarter/half a second, and then it would appear. What are your thoughts?

## Unshelfed
![progress-hidden](https://user-images.githubusercontent.com/18221058/118887795-b4615f80-b8af-11eb-8e5c-97924945e1f8.gif)
## Showing
![progress-showing](https://user-images.githubusercontent.com/18221058/118887806-b7f4e680-b8af-11eb-9c9d-88de1659e7f8.gif)

**Comment by coiko** [comment]
@KianBadie I certainly wouldn't call that glaring!  I don't think it's a problem at all.  I guess it would probably be better if the knob was missing and then appeared when it loaded so the motion wouldn't catch the eye as much.  So if that's easy to implement, I'd go for it.  (Otherwise, it's fine the way it is.)  

My only suggestion style-wise would be to make the toggle smaller so it's the same height as the "Progress" text.  What do you think?

Thanks!

**Comment by KianBadie** [comment]
@coiko My apologies! I know this small thing has been taking a while. The last thing I wanted to possibly touch up on is the coloring/wording of the toggle. Even though the contrast made sense to me on paper (white border, so the inner dark-blue would have sufficient contrast with the border even though it does not have sufficient contrast with the grey background), I found that I wanted to at least see if there was something more obvious. I attached a gif of one option, that uses black and light grey to denote on and off, which has sufficient contrast between everything. What do you think?

I was also thinking of the possibility of changing the wording a bit to be even more obvious. Something like:
Progress On [    o]
Progress Off [o    ]
So the words "on and off" would change depending on the switch. What do you think?

Other than that, I am pretty much ready to merge it and return to it later to add in some of those other features (like pop up menus for the chapters).

## Gif
![progress](https://user-images.githubusercontent.com/18221058/119417010-c4ab7d00-bca9-11eb-8d2d-1326a743474f.gif)

**Comment by coiko** [comment]
@KianBadie Sorry for the slow response - I wanted to sit on this and see it fresh.  I really like your updated toggle - it's much clearer to see on vs. off with the lighter fill!  My only hesitation is that we don't use black on the site, and I'm wary of adding colors to the theme.  What about replacing the black outline/dot with the dark blue-green?

I also really like your idea of making the wording more obvious!  If we don't want to have to change the wording (which might be problematic during that loading period), what do you think about just saying "Progress Bar"?

**Comment by KianBadie** [comment]
@coiko As always, no worries! I hear you, I tried replacing it with the blue-green and it was not enough to meet contrast requirements when the toggle was off. I darkened it a bit to meet the requirements and, while not the same, it still has the blue-green quality. What are your thoughts on this? The gif is below.

Ah yes, I completely overlooked that in my considerations. The loading period could make the initial state of the on/off wording a little jarring. For the wording, I feel like "Progress Bar" could work. But I feel like it has the same quality as "Progress" as they're both nouns when maybe an action phrase could be more direct. How do you feel about "Show Progress"?

## Gif
![progress](https://user-images.githubusercontent.com/18221058/119537410-dc811080-bd3e-11eb-85c7-1a9e8f58b216.gif)

**Comment by coiko** [comment]
@KianBadie Looks great!  And yes, I think "Show Progress" would be perfect.  Thanks!

**Comment by KianBadie** [comment]
@coiko Fantastic! I will go ahead and make those changes and merge it into the site very soon!

**Comment by KianBadie** [comment]
@coiko Just pushed the changes! Please let me know of any bugs or thoughts/opinions that come up and I will be happy to work on it!

**Comment by KianBadie** [comment]
@coiko Here is the fix for the line wrapping in the footer that I was mentioning in our meeting today. I feel like it is more subtle than a font decrease, but at some point (like at about 2/3rds of my screen) "A PUBLICATION OF THE CALTECH LIBRARY" starts to take up more space than the other elements while the other elements take up equal space, so I don't think everything is centered like it used to be. Does this look good to you, or do you think we should use another method like decrease the size of that text at some point?

## Gif
![footer-linewrap](https://user-images.githubusercontent.com/18221058/120051032-e5d6db00-bfd3-11eb-8747-8485d0794383.gif)

**Comment by coiko** [comment]
Perfect!  Thanks @KianBadie!

**Comment by KianBadie** [comment]
@coiko I just merged those changes, so they should show up soon! As for re-centering the text/video, would you like the elements to re-center when the progress bar is shelved/opened? Or would you like the elements to stay in the same position even when the progress bar is shelved?

**Comment by coiko** [comment]
@KianBadie It looks great!  As for re-centering (or not) when the bar is shelved, I don't have a preference so I think you should do whatever's easiest and/or seems more natural to you.  Thanks!

**Comment by KianBadie** [comment]
@coiko Sounds good! I went ahead and merged those changes. If you decide that re-centering the elements is actually needed, just let me know! I also added a drop shadow to the progress marker so that when the marker does overlap with the video border, it is a little bit more visible than before. The overlap will only affect the marker now, instead of the whole progress bar.

**Comment by coiko** [comment]
Thanks @KianBadie!  It looks perfect to me!

**Comment by KianBadie** [comment]
@coiko In an earlier email I explained a bug with the progress bar where the pop up menu was not accessible when a modal was open. Trying to fix this showed me an even bigger bug. The issue is that the space taken up by the progress bar is not covered by the modal overlay when the bar is shelved. I attached a gif of the problem, as well as a picture since the gif does not make it very clear. I wanted to clarify the desired behavior before attempting to fix this. 

So I know that we wanted the inner content (video, slider, and text content) to be centered vertically with the progress bar in mind (as in the progress bar is not "floating" and takes up actual vertical space). When the bar is shelved, should the inner content stay in the same spot, or be re-centered with the new available space in mind? Whichever the answer is, I'm not sure how feasible it is to fix this bug without having to restructure some big things in the HTML hierarchy, which sounds like it has the possibility to break more than it will fix. Unfortunately, the way I initially wrote things might have this bug in a tangled mess and a good solution might have to wait until I can give that part of the code a deep clean. If all else fails, how do you feel about the progress bar "floating" on top of the footer. As in the page is centered in a way where it is not aware of the progress bar. I know it is not desired, but it seems like the easiest fix for this bug that keeps the site presentable.

## Gif
![progress](https://user-images.githubusercontent.com/18221058/127363100-468df570-b24d-4ecb-875c-83da21e8ee48.gif)
## Screenshot
![progress](https://user-images.githubusercontent.com/18221058/127363117-82b60e8e-1586-4048-adc0-afea4478815f.PNG)

**Comment by coiko** [comment]
Thanks for explaining this @KianBadie!  I have to confess that I don't really see the problem.  The behavior all looks great to me.  I like that the page elements don't recenter when the bar is hidden (I think that would be distracting), and I think it makes perfect sense not to be able to hover on the progress bar when a modal is open since the modal is an "extra" page and only the main pages are counted by the indicator.  

Let me know if I'm missing the problem.  We can also discuss in person Friday (or sooner) if that's easier.  Thanks!

**Comment by KianBadie** [comment]
@coiko No problem! It is a bit hard to notice, especially in the pic and gif I attached. The problem is on the testing site if you haven't checked it out there already. When you open a modal with the progress bar shelved, there will be a empty space in between the footer and the modal overlay. It might be hard to notice because the background and footer color are similar. If it is still unnoticeable, then I would be happy to discuss on Friday to see if it is worth fixing!

Not being able to hover over the progress bar when the modal is open makes things easier! In that case, would you want the modal overlay to cover the footer as well? Right now, it only covers the marker.

**Comment by coiko** [comment]
Ah!  I finally see it!  Thanks for the extra explanation @KianBadie.  I don't think it's any problem at all.  It's very subtle (I think the vast majority of users won't notice it) and it sounds like the fix (floating the progress bar) might be more visually distracting by introducing overlap on short screens.  So I vote for leaving this until potentially a "deep clean" in the future.

As for the modal overlay, yes, it might be nice (more real estate!) to have the modal overlay cover the footer (and have the footer greyed out like the main section).  If that's a lot of work, though, don't worry at all - it looks great as is, and you have the full-screen coverage on mobile where the real estate really matters.  Thanks!

**Comment by KianBadie** [comment]
@coiko No problem and sounds good! If it moves up the priority list, please let me know and I will be happy to work on it and make a more desired behavior.

My apologies, I realized I misused some words in my earlier comment. I meant to say "would you want the modal overlay to cover the progress bar" instead of "footer". However, if you like the behavior you described, I can try to make that work! If it means anything, I personally think having it only cover everything up until the footer looks nice. It makes it seem like the content is in a window for me, where the header and footer are the frame. However, I just realized that this is the exact predicament we are in, where getting the overlay to cover the progress bar might be better suited for a deep clean. 

What are your thoughts on that? Should it still cover the whole footer or something else?

**Comment by coiko** [comment]
@KianBadie Ah perfect!  I'd leave it as is then, covering neither the footer nor the progress bar.  I agree that the sense of content in a window is nice, so let's go with that.  Thanks!

**Comment by KianBadie** [comment]
@coiko Sounds good, I will leave it as is! And no problem!

**Comment by KianBadie** [comment]
@coiko How do these look for the progress toggle width? 

## Around double width
![progress](https://user-images.githubusercontent.com/18221058/128067769-59723263-f581-4c0c-8191-981d6e0bd56c.gif)
## Extra wiggle room
![progress2](https://user-images.githubusercontent.com/18221058/128068081-8de1eddc-0012-45ab-a9f3-92849c24f98e.gif)

**Comment by coiko** [comment]
@KianBadie Looks fantastic - thanks!  I think the first one is perfect.  What do you think?

**Comment by KianBadie** [comment]
Personally I like a little more wiggle room, but I think in the end I like to side with your ux preferences. I don't know any objective sources on toggle switch guidelines regarding size, so for now I happy to merge the first one and we can discuss if anything else comes up!

**Comment by coiko** [comment]
@KianBadie Nope, definitely go with more wiggle room then.  I trust your instincts on design.  Plus, when I google "toggle icon" the vast majority look just like your second example.  So please go with that!
