### ISSUE TITLE
Section Page fixes

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#11]
Issue to discuss bug fixes/improvements on the section pages.

**Comment by KianBadie** [comment]
@coiko Did we still want to increase the line height of all the text? If so, would this just be on desktop or mobile as well? And did we want this to affect all text (appendix pages, references page, chapter pages etc)? Currently, all the pages have the same line height as the section pages.

I know this small thing has the possibility of requiring observation of a good amount of small aspects of the site, so please feel free to answer at your convenience. I just decided to tackle some small issues in between the bigger projects, so I can put this down/pick it up whenever!

## Bumping up the line height
![line-height](https://user-images.githubusercontent.com/18221058/119574122-10256000-bd6a-11eb-84ae-c3b024421ba0.gif)

**Comment by coiko** [comment]
@KianBadie Yes!  This looks awesome!  (I think it's easier to read.)  And yes, I think this should apply to the text everywhere, including the appendices and the mobile version.  Thanks!

**Comment by KianBadie** [comment]
@coiko Sounds good, I will go ahead and add that then!

**Comment by KianBadie** [comment]
@coiko I increased the line height a bit on both desktop and mobile! Please let me know if further tweaking is needed.

**Comment by coiko** [comment]
@KianBadie It looks great!  Thanks so much!

**Comment by KianBadie** [comment]
@coiko I started implementing an "enlarge" functionality for the subsection images. Is the gif below along the lines of what you were thinking? I added our usual grey border to match the other elements and to have an encapsulating divider between the image and background when enlarged. In the gif, it looks like the dimensions are changing, but that is just because the image is adding white side bars to maintain 100% width but normal ratio height.

For mobile, do you think it would be good to have the same thing as the sliders, where they go full screen?

## Gif
![image-enlarge](https://user-images.githubusercontent.com/18221058/120558567-85211700-c3b4-11eb-8b8d-01384ca6ba25.gif)

**Comment by coiko** [comment]
@KianBadie This is beautiful!  And yes, I think the full-screen option similar to the sliders would be perfect for mobile.  Thanks!

**Comment by KianBadie** [comment]
@coiko I just merged the expandable image changes, so they should be available soon! Because the images became smaller in general to account for the grey border, I ended up bumping up the height of the images on mobile (which is more noticeable on landscape). It might look the same as before, but please let me know if you think further tweaking is needed for that aspect or this feature in general!

**Comment by coiko** [comment]
@KianBadie They look fantastic!  Thank you so much!

**Comment by KianBadie** [comment]
@coiko I adding some padding in between the text and the scroll bars in the main section. In the fix I did, it ended up right aligning the scroll bar instead of having space between the bar and the edge of the page, and I thought it looked good. I attached screenshots of the differences below because I wanted to check your thoughts. These changes are also on the testing site if you want to see it in action. If you liked how it was style before, feel free to let me know and I can try to style it like it was with the new padding!

## New
![windows_new](https://user-images.githubusercontent.com/18221058/129457072-ecef3107-2744-42d8-a48b-5e9024b1a629.PNG)
![mac_new](https://user-images.githubusercontent.com/18221058/129457074-a6c65918-91ec-4e58-8593-361300f729a3.gif)
## Old
![windows_old](https://user-images.githubusercontent.com/18221058/129457080-dc89c747-b3da-454e-bb5d-5dae8ea855d2.PNG)
![mac_old](https://user-images.githubusercontent.com/18221058/129457082-36c412ca-4c82-4ecc-a5ad-69d44a525708.gif)

**Comment by coiko** [comment]
Oh perfect!  It looks great (I really like the right-aligned scrollbar).  Thanks @KianBadie!

**Comment by coiko** [comment]
@KianBadie In fact, it looks so good, do you think it would be worth doing the modals the same way?

**Comment by KianBadie** [comment]
@coiko Awesome! Yeah, I would be happy to try to get the same on the modals!

**Comment by KianBadie** [comment]
@coiko Here is how things look with the update to the modal. My personal vote is that I like the scrollbar the way it was before when it was aligned with the video. I thing the screen-edge aligned scrollbar looks good on the main section, but I think in the modals I like it not on the edge because there is a video component in there, so I like it aligned with that. What are your thoughts? If you think it looks great, then it looks great to me too!

## Screenshot
![modal-scrollbar](https://user-images.githubusercontent.com/18221058/129773702-e2822dd8-f06e-462e-86bc-40e2a0da69a6.PNG)

**Comment by coiko** [comment]
@KianBadie Agreed!  Thanks so much for testing it, but yes, let's leave it aligned to the edge of the video.

**Comment by KianBadie** [comment]
@coiko No problem, and sounds good!
