### ISSUE TITLE
Appendix Page fixes/updates

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#14]
Issue to discuss bug fixes/improvements on the appendix pages.

**Comment by KianBadie** [comment]
@coiko I was just about to get started on enhancing the appendix dropdown menus to be expandable by clicking the profile name/feature name. After doing some searching, it seems like an accepted functionality is to have the whole header element (text, expand icon, and space in-between) be one long clickable button ([World Wide Web Consortium example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html) and [Google's example](https://www.google.com/search?q=google+question&rlz=1C1ONGR_enUS949US949&oq=google+question&aqs=chrome..69i57j0i131i433i512j0i433i512j0i512l2j69i60l3.4209j0j4&sourceid=chrome&ie=UTF-8) that shows up in search results). While I haven't found anything explicitly stating that this is best practice, would you like the adopt the same functionality? Or do you prefer only the button/title being clickable (not the space in between)?

**Comment by coiko** [comment]
@KianBadie Yes - that sounds perfect!  It's funny, because that was my initial intuition as well, so I must have experienced it on other sites.  Thanks!

**Comment by KianBadie** [comment]
@coiko Sounds good!

**Comment by KianBadie** [comment]
@coiko I just pushed the appendix accordion menu enhancements to our testing site. It added the behavior to make the whole header be clickable to toggle the dropdown menu, as well as making them tab-able with the keyboard. It also fixed the bug where the feature index links would be tab-able even though the dropdowns was closed. These updated dropdowns are on the feature index, profile, and about pages.

In addition to that, there were numerous small things that got changed/tweaked as an effect of reworking the menus. Some of them can be considered improvements, but other changes seemed neutral (new or old style could be preferred). Here is a list of the other small changes. If you think any of them are a step backwards, please let me know and I can modify them!
- Headers for the dropdowns vertically center the title/plus button. On the old site, they were off centered before.
- Removed extra space that existed between feature index list and its header
- Spacing between headers is different (desktop and mobile) as a result of things being more centered/rewritten. There is less space between the header text and the white horizontal separator, causing the whole list to be raised up slightly since there is less empty space.
-  A little more space in between feature index entries.
- Profile images have a little less space between it and the profile description.
- Removed empty space at top of profile description on desktop. Now, it is horizontally aligned with the profile image.
- Profile containers have some padding space between it and the following profile header.
- Changed the anchor for the what's new section. Now, clicking on the link will take you to "/about.html#WhatsNew"

If it would be helpful to see some comparison screenshots, I would be happy to take and provide those! I will be doing some rounds of checks on the dropdown menus to try to catch any bugs that might have slipped past my first iteration of this. If you notice anything please feel free to let me know. One thing that I plan on checking in the wild is the old bug where the profile descriptions in profile menus were cut off on mobile portrait orientation due to the profile image loading after the menu was opened. When I was attempting to re-add that bug-fixing functionality, I was not able to replicate the bug, so I left it out. If I encounter the bug again however (or if you do), then I can add that back in.

**Comment by coiko** [comment]
@KianBadie This is fantastic - thank you so much!  Checking out the test site, I'd say everything on the list is an improvement.  I'll let you know if I notice anything (like the profile cut-off bug) but so far everything looks perfect!

**Comment by KianBadie** [comment]
@coiko I re-added the functionality to fix the cut-off profile components.  Please let me know if you still see the bug on your end!

**Comment by coiko** [comment]
Wonderful - thanks @KianBadie!
