### ISSUE TITLE
"Preview" version handling post-update to "main"

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#15]
Once the "preview" version of the site merges into the "main" version, how should visits to the "preview" version be handled?

**Comment by KianBadie** [comment]
@coiko What do you think about Tom's recommendation to have a redirect to the "main" version from the "preview" version? Do you think that would be a satisfying way to handle the preview version once the main version is updated?

**Comment by coiko** [comment]
@KianBadie Yep, a redirect sounds like a great solution to me.  What do you think?

**Comment by KianBadie** [comment]
@coiko It sounds good to me as well, would you want to follow Tom's advice on only having it on the landing page as well? Or do you think the other pages should redirect?

**Comment by coiko** [comment]
@KianBadie It's up to you.  I think either way is fine, so I'd go with whatever's less work (which sounds like just the landing page).  Thanks!

**Comment by KianBadie** [comment]
@coiko Sounds good, I will go ahead and just do the landing page then!

**Comment by coiko** [comment]
I think that sounds perfect.  Thanks @KianBadie!

**Comment by coiko** [comment]
@KianBadie That sounds good to me.  (I agree that few users should encounter the redirect, and even fewer the message, but for those that do, I think it's perfect.)  Thanks!

**Comment by KianBadie** [comment]
@coiko no problem!
