### ISSUE TITLE
Videos unplayable after quality switching on Android

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#16]
After quality switching a couple of times, videos become unplayable on Android.

**Comment by KianBadie** [comment]
@coiko I spent some time investigating this bug. I was able to replicate consistently. However, I was only able to replicate it on an older device. On newer devices, I was switching qualities sporadically with no problems. I was also able to find a specific error it was giving, and a description of that error: "Despite having previously been determined to be usable, an error occurred while trying to decode the media resource, resulting in an error." It looks like it might be an error that came about internally in the browser's video player. My current theory is that this used to be a problem in their video player, but they fixed it later on.

Under what circumstances did you experience the bug? Would you happen to know the exact phone model and version number? It could be coincidence that I have not experienced it yet on newer devices.

**Comment by coiko** [comment]
@KianBadie Thanks for looking into this!  It's funny because I can't seem to trigger it now on my device.  (Before I would run into it the same way it sounds like you were: I'd switch quality once, twice, or maybe three times and it would go unresponsive and show the broken video icon.)  I did a software update recently, so I wonder if that fixed it?  I have a Pixel 3 XL and it looks like it's running Android version 11.  So maybe it's not something we need to worry about.  What do you think?

**Comment by KianBadie** [comment]
@coiko No problem! Well that is indeed good news to hear. That's interesting you would get the broken icon. When I run into it, I would get no icon. I think it is possible we might not need to worry about it, but I will keep an eye on this bug and return to it periodically to make sure it is not very prevalent. One other odd thing I noticed is that the browser versions of the 2 device I used (those devices being a newer Android version/model and an older version/model) looked like they were using the same version of Chrome. That added more mystery as I don't know why the same browser versions would act differently on different OS versions, unless they are somehow tied.

As of right now, it seems that this issue might only happen on older devices after switching video qualities a couple of times. If someone did fit the bill to experience the bug, refreshing the page seems to bring the video back (which hopefully the user does). Though not ideal, I think that qualifies it as non-critical. How does that sound to you?

**Comment by coiko** [comment]
Sounds perfect.  Thanks @KianBadie!

**Comment by coiko** [comment]
@KianBadie I haven't.  And based on your testing experience, it sounds like it's still a non-critical bug.  What do you think?

**Comment by KianBadie** [comment]
@coiko Agreed. In that case I will put it to rest!
