### ISSUE TITLE
Merging update 2.0 from preview to main

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#17]
Updating the "https://www.cellstructureatlas.org/" version of the site to match the "https://www.cellstructureatlas.org/preview/" version of the site. Planned date is September 3rd. Todo includes:
- Creating redirect landing page for preview version
- determine if site needs bug-fixing/rebuilding before September 3rd.

**Comment by KianBadie** [comment]
@coiko I have been continuing to check the preview version of the site to determine if there are any critical bugs that need fixing and would warrant a rebuilding of the site before the update. I wanted to run by you the list of bugs I have found so far that I thought held some significance since we have updated the preview:
- Changing orientation on iOS while in protein viewer resizes incorrectly. Protein viewer is half the size of the container (this has not happened consistently across iPhones, I need to test more to see how consistent this is)
- Broken reference link for tsien2005
- Minimizing the full-screen Phylogenetic tree view on iOS prevents it from utilizing the full-screen functionality again properly. On portrait, the full-screen tree viewer will now only be 1/3rd of the page. On landscape it works as normal (please let me know if you would like to see this, this feels like a major one)

I will still be doing checks and add any more significant bugs I find. But for now, I wanted to get your thoughts on these bugs. Would you like to see any of them in action to assess more? Do any of them sounds major to you?

**Comment by coiko** [comment]
Thanks @KianBadie!  I'd say the broken reference link is minor, so I'd only fix it if something else warrants a rebuild.  The other two seem a bit more major and I can imagine a user encountering them.  I'm guessing the first one is easy to circumvent by just closing and reopening the viewer in the desired orientation, but it sounds like the last one might be harder for a user to clear.  Do you just need to refresh the page?  And how widespread do you think it might be?

Ultimately, I leave it up to your discretion what to tackle (or not) before the update.  I don't think we've run into anything that renders the site unusable so I think it's fine to go ahead as is, but if this is a handy juncture to fix things, it does sound like there are a few things it would be good to fix before too much longer.  What do you think?

**Comment by KianBadie** [comment]
@coiko No problem! I'm excited that we are almost at the end of 2.0! I think a a refresh will fix the iOS bug and I think it unfortunately would exists on all iOS devices. I think both the protein viewer bug and the tree bug should have some convenient solutions to fix them, so I can try to push some changes today or tomorrow and I think that would be enough time pre-update to let things sit and make sure a super unexpected bug arose because of the fix. While I'm at it, I can manually change that reference link as well. Would you happen to have the correct one?

**Comment by coiko** [comment]
That would be fantastic - thanks @KianBadie!  And if you don't mind manually fixing the reference link, it's:
http://tsienlab.ucsd.edu/Publications/Tsien%202006%20Harvey%20Lectures%20-%20Breeding%20Molecules%20to%20Spy.pdf
Thank you!

**Comment by KianBadie** [comment]
@coiko No problem, and thank you for the link!

**Comment by KianBadie** [comment]
@coiko So the link and phylogenetic tree issue are already fixed! I just pushed the changes to our testing site ("https://caltechlibrary.github.io/cell-atlas/" site, funny that we have "preview" now too) so they should be reflected soon!

**Comment by coiko** [comment]
Oh fantastic!  Thanks so much @KianBadie!

**Comment by KianBadie** [comment]
@coiko I believe I found the culprit to that iOS protein viewer resizing bug I mentioned. The protein viewer resizes on a built in browser event that fires when the screen is resized (so orientation changes would trigger it). However, it looks like (on iOS at least) that event only fires after the page is completely loaded. So things were resizing correctly on iOS, but only after everything was loaded. I might have not seen this yet because the iPhones on the service I used maybe had fast connections.

There is a deprecated browser event that fires on orientationchanges. It seemed like it fired even before the page was loaded. I think a quick and possibly satisfactory (though not ideal) fix is to try to use this deprecated event along side the resize event until we can figure out a way to correctly avoid this bug. I will let you know how things go!

**Comment by coiko** [comment]
Wonderful - thanks @KianBadie!

**Comment by KianBadie** [comment]
@coiko Unfortunately, my experiment to fix the protein viewer display did not work. After doing some more investigating today, I have a possible other experiment that shouldn't be too hard to implement. It looks like the browser functionality to notify of screen resizes happens after a threshold of loading is complete (at least on iOS). The PDBs are somewhat large files, and Google's report marked them as large files that impacted page performance (a topic that will be interesting to tackle post-update). I am wondering if that is stalling the the page from meeting the loading threshold. One idea I could test out is to load the PDB once the modal is opened, or maybe after the page has loaded. That way, the series of events could hopefully be:
1. Load the page (excluding the PDBs)
2. The browser turns on resize events because the initial page is loaded
3. When PDB is opened, it will resize correctly

As opposed to:
1. Attempt to load all resources
2. Open PDB
3. Experience incorrect resizing
4. Page loads and now correct resizing is experienced

I can send a screen recording of what this looks like through email if you would like to see. Unfortunately, I can't do a gif since the devices I test through my computer have pretty fast internet, so I can't even replicate the bug. I know this seems like a lot for one last bug in our pre-update checklist. However, it felt like a worthy thing to consider as it did not feel like the bug would be too rare to encounter. 

Have you experienced anything on Android? Now that I think about, the bug does come up when I take a dive for the protein viewer immediately once the page loads. That might not be a common use case, but it feels like the browser needs ~20 seconds to work correctly, which does not seem like an unreasonably short time. What are your thoughts on this? And unloading this wall of text!

**Comment by coiko** [comment]
@KianBadie That sounds like a great plan!  And no, I haven't experienced the resizing issue on Android, even when I just deliberately tried to open the viewer as soon as possible after loading a page.  I have pretty fast internet, though.  The only issue I've noticed is that the largest structure (3j31 in section 10.8) won't load on my Android phone.  (Sometimes the viewer just stays blank and sometimes it eventually goes to a black (blank) background.)  I think that's fine, though.  It takes a long time to load on desktop, too.  In the future we can think about further cutting the size of that file, for instance by only showing half the structure, but for now I think it's fine.  So to get back on point, I haven't experienced the issue so I can't shed any additional light, but I think your plan for tackling it sounds great!

**Comment by KianBadie** [comment]
@coiko Sounds good! I already pushed the changes to our testing site (it was very simple to add, so it can be removed just as easy if the side affects are not desirable). So you are able to test it now and see if the core experience was altered too much (which I will be doing as well). That's good to know you did not experience anything. The one android phone I have only connects to wifi and is pretty old, so it's hard to trust it with testing this kind of responsiveness.

Yes, that could be something worth looking into. Checking the 10.8 pdb out now, I am experiencing the same thing. One positive side affect of the loading experiment is that now the phone won't try to load that massive pdb until the modal is opened.

The one negative side affect that this introduces now (on both Android and iOS) is that because the PDB file is loaded later rather than sooner, the protein viewer will be left "blank" for a longer period of time. When the pdb was loaded immediately, there was a high chance that the structure would be visible in the viewer when it is initially opened. Now, that chance is lower since loading starts later. I feel like the ideal solution would be something along the lines of having this new style of loading (deferring loading of certain resources until needed usually seems like a good idea) with a icon or animation to show loading, but unfortunately it seems we have to consider the tradeoffs of each option without that. Other than that though, I am unfortunately not sure how to circumvent this bug pre-update. My apologies!

**Comment by KianBadie** [comment]
@coiko Also, I know in the past we have waited until the offline version of the site was built before testing it and giving it the seal of the approval. If you would like to, I can send you an offline version that will reflect what the final offline version looks like. You would just need to insert the videos/comparison images folder yourself, since it would be too big for caltech dropbox.

**Comment by coiko** [comment]
Thanks @KianBadie!  I just checked out the new behavior on my phone and it looks good!  I agree that ultimately it will be ideal to add a loading indicator, but I think it's great as is for this update.

As an odd aside, when I was manipulating the structures in the protein viewer a lot to test this issue, I noticed that occasionally it would detect a residue selection and show the residue information.  I thought that was a desktop-only feature, and I still don't know how exactly I triggered it (besides spastic tapping)?  Anyway, I pass it along merely as a point of curiosity.

And yes, it would be fantastic if you could send along the offline version(s) for testing whenever they're ready.  Thanks!

**Comment by KianBadie** [comment]
@coiko The feature is actually available on any device! Would you prefer for it to be only on desktop?

And sounds good with the offline version! I will send a zip over the dropbox and an email describing the few extra steps to get it working.

**Comment by coiko** [comment]
@KianBadie Ah, that's great!  I don't know why I had the idea that it was desktop specific.  I think it's great to keep it, but at some point in the future we might want to finetune it a bit on Android since it only seems to work once every 10-20 taps for me.  (It's also very possible that my personal tapping style is problematic.)

Thanks for the offline versions!

**Comment by KianBadie** [comment]
@coiko I know we have had plenty of desktop vs mobile feature discussions, so I wouldn't be surprised if we talked about this and I accidently kept it in too! And ooh yeah that is not a good experience, it would definitely be nice to touch up that feature.

No problem! Please let me know if you have any questions or if anything comes up!

**Comment by KianBadie** [comment]
@coiko It looks like this is going to be the thread to discuss all the minor bugs that are getting worked on pre-update. Just wanted to let you know that there was a significant bug I just fixed where scrubbing on the modal videos was not working (the scrub images would overlay over the video even if the video was playing). Just wanted to let you know just in case something felt fishy about those videos and so that if you notice any other bugs with the videos we know it might be linked to this new fix. From my testing and the simplicity of the bug, I think the fix I just pushed will be work out well though.

**Comment by coiko** [comment]
Wonderful!  Thank you so much @KianBadie!  (And yes, it was completely off my radar.)

**Comment by KianBadie** [comment]
@coiko No problem!

**Comment by KianBadie** [comment]
@coiko I have pretty much completed the bulk of the things I wanted to check before the update. The only 2 new notable bugs that I have found are:
- On android, sometimes the dropdown menus (nav menu and appendix pages) would resize incorrectly on orientation change. This results in the dropdown being having extra space at the bottom or cutting off some of the items in it. 
- On iPhone 11, closing the protein viewer and trying to open it again would result in a "blank" protein viewer until the orientation is changed. Strangely, this would not happen on iPhone 12 or on an iPhone XS.

While these bugs are notable, I assessed them as being ok to leave as is going into the update. What is your thought on that?

**Comment by coiko** [comment]
Thanks for checking everything out @KianBadie!  And yes, I concur that these bugs are minor and fine to leave in the update.

**Comment by KianBadie** [comment]
@coiko Sounds good! In that case, everything looks like we are good to go! I have emailed Tom that everything is ready to go for tomorrow. Exciting! I will see you tomorrow at our meeting. Until then, enjoy the rest of your day!

**Comment by coiko** [comment]
Wonderful!  Thanks @KianBadie!

**Comment by KianBadie** [comment]
@coiko Just checking in to make sure my email didn't accidently go to the spam folder again. If your still in the process of double checking things, no worries!
