### ISSUE TITLE
Redirect of all preview pages

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#18]
Create files for preview version of site to redirect all the pages to the main version.

**Comment by KianBadie** [comment]
@coiko The wording for the redirect of the landing page was "The preview version has been released as the main version at https://www.cellstructureatlas.org/." This makes sense for the landing page, but would you want a different wording for the rest of the pages? Maybe something along the lines of "The preview version of this page has been released on the main version at https://www.cellstructureatlas.org/1-10-putting-it-all-together.html." Or do you think the original wording is satisfactory?

**Comment by coiko** [comment]
@KianBadie I think the modified wording you proposed is great!  Thanks!

**Comment by KianBadie** [comment]
@coiko Sounds good and no problem!

**Comment by KianBadie** [comment]
@coiko All the preview redirects are up! If you visit the pages on the preview version, it should redirect you to the main version instantly. Please let me know if you notice anything unintended.

**Comment by coiko** [comment]
Beautiful!  Thank you so much @KianBadie!  My quick check of some random pages worked like a charm.

**Comment by KianBadie** [comment]
@coiko No problem!
