### ISSUE TITLE
Mobile rework

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#2]
### Overview
Optimizing the display of the overall site for mobile devices.

### Action Items
- [x] Create wireframes/mocks
- [x] Implement on a new branch
- [ ] Gather feedback
- [ ] Implement changes in response to feedback

**Comment by KianBadie** [comment]
This week, I worked on creating some wireframes/mock ups of what the section pages could look like on mobile. I attached the link of my Figma file (UI/UX tool) for those who want to check it out. To just see what the wireframes/prototypes looks like, I have attached links to the prototype program that Figma provides. This tool is a bit new to me, so if anyone has problems with the links, please let me know. If everything works out, this will prevent me from having to paste many screenshots and taking up lots of space!

From our meeting today, @coiko and I decided the layout for section pages should have a binary style layout where either the video or the section text will be showing, but not both. We also decided that when videos are played, they will automatically go fullscreen. It seems this is default behavior for how iOS treats `video` tags, I will have to do some research to replicate on Android. I also made a Youtube/Vimeo style wireframe (both text and video can be on the screen), which I also attached below if anyone wanted to check it out and had comments on it.

@coiko I forgot to add the video citation information for the mock ups that I showed you today. Hopefully I can add them in and they will be reflected in the prototype links below. I'll try placing it in different spots, but if you have any ideas for placement that you think will look good please let me know!

Feedback/opinions are very much welcome and very much needed! 
 
## Links
- My Figma file of the wireframes for those interested: [link](https://www.figma.com/file/Zk4lGzmVZD1DNeLWTNrJhf/Cell-Atlas-Mobile?node-id=130%3A81).
- Link to prototypes:
   - [Binary Portrait mode](https://www.figma.com/proto/Zk4lGzmVZD1DNeLWTNrJhf/Cell-Atlas-Mobile?node-id=169%3A265&scaling=scale-down)
   - [Binary Landscape](https://www.figma.com/proto/Zk4lGzmVZD1DNeLWTNrJhf/Cell-Atlas-Mobile?node-id=169%3A2&scaling=min-zoom)
   - [Vimeo/Youtube style portrait](https://www.figma.com/proto/Zk4lGzmVZD1DNeLWTNrJhf/Cell-Atlas-Mobile?node-id=102%3A2003&scaling=scale-down)
   - [Vimeo/Youtube style landscape](https://www.figma.com/proto/Zk4lGzmVZD1DNeLWTNrJhf/Cell-Atlas-Mobile?node-id=169%3A604&scaling=scale-down)

**Comment by coiko** [comment]
@KianBadie These are fantastic!  The modals look great, too!  I like the second example in the Binary Landscape prototype, where the background blurs out - it makes it clear that it's a separate popup from the page and it gives some more real estate for what would otherwise be pretty squeezed with both video and text.  As for the video citations, you could try putting them at the bottom of the text section (maybe even below the Learn More buttons) since they won't be used as much and it would be a shame to clutter up the video view with them.  But please try anything you think will work best.  Thanks!

**Comment by KianBadie** [comment]
@coiko Sorry for the delayed response, I checked out for the weekend but am checking back in now. I definitely agree with the landscape comment you meant about the modal (at least I am assuming it is about the modal). It looks like it could use the extra screen space.

For the video citation section, I whipped up some prototypes to pick from (since the placement wasn't as straightforward as the general layout). Here are the prototypes:
- [Portrait](https://www.figma.com/proto/Zk4lGzmVZD1DNeLWTNrJhf/Cell-Atlas-Mobile?node-id=214%3A298&scaling=scale-down)
- [Landscape](https://www.figma.com/proto/Zk4lGzmVZD1DNeLWTNrJhf/Cell-Atlas-Mobile?node-id=214%3A560&scaling=scale-down)
I added some examples of titling the video citation section. Since it's on a different "page" than the video, I thought it could use some context with the title. I titled it "video notes" for now, as I wasn't sure if "Video Citation" was just what we called it for short, or if that should be the actual name.

I created these for the binary views only, as I am assuming the youtube/vimeo prototypes are just possibilities to keep in mind. However, I would also be happy to create the prototypes for those if desired to see what the video citations would look like with those layouts!

**Comment by coiko** [comment]
Thanks @KianBadie!  These are beautiful!  It's very helpful to see the different prototypes (and yes, just using the binary formats is great).  I like the first option, where the info appears at the bottom.  I think it makes sense since it will be used less than the Learn More buttons.  I'm also leaning toward leaving the section unlabeled (although Video Notes is a great title!) because of the limited space.  We've been thinking about expanding the Intro video a bit to include some interface navigation, so I think if we familiarize readers with that section at the beginning, it won't need a title throughout.

**Comment by KianBadie** [comment]
@coiko Thank you, and sounds good! I will leave out the title for now then and if needed we can add it back in. Ah I see, yeah that intro video could be very helpful for the navigation. 

I plan to make some quick wireframes today of the pages I have left out so far (chapter pages, landing page, appendix pages) just to know what I'm working towards as well as to open the floor to layout changes ahead of time. Like we mentioned earlier, the layouts for those pages already work nice with mobile, so it would probably be some small changes to make it fit just right. After that, I will start the process of implementing this into the site!

**Comment by KianBadie** [comment]
@coiko Here are the prototypes for the other pages:
- [Portrait](https://www.figma.com/proto/Zk4lGzmVZD1DNeLWTNrJhf/Cell-Atlas---Mobile?node-id=232%3A470&scaling=scale-down)
- [Landscape](https://www.figma.com/proto/Zk4lGzmVZD1DNeLWTNrJhf/Cell-Atlas---Mobile?node-id=232%3A913&scaling=scale-down)

I skipped doing prototypes for the references and phylogenetic tree pages since I figured they would work pretty similar in idea to the appendix pages I did do in the linked prototypes. Some main points that I noticed while making these and wanted to get your thoughts on were:
- The "controls" bar at the bottom of the screen no longer have video/text options. At first, I considered just putting the white arrows with no dark grey background bar. However, I figured it might be nice to have consistency throughout the pages, with the grey bar always being there.
- In portrait mode, it seems that profile descriptions might have have little space as the text sections are the same height as the images. I imagine it might get even trickier with some of the wider profile pictures. At the moment I don't have a response to that in mind. However, things look good on landscape so far.
- On landscape, I forgot if we decided if the controls bar at the bottom would float to the bottom of the page, or if it would stay fixed at the bottom of the screen. My take is that the controls bar at the bottom of the screen would take up to much space, and should float to the bottom of the page (both options are in the landscape prototypes). However, I am not sure if the floating to the bottom should happen in landscape for chapter pages, as it would require the reader to scroll a tiny bit to go to the next page. As there isn't much information on the chapter pages, I figured to have it fixed at the bottom of the screen. It does make the reading area seem a bit small however.
-  I wasn't sure what to put as the title of the pages in the top nav bar for the chapter pages and the appendix pages. For now, I put the title for the chapter pages as "Chapter <X>" and for appendix pages I put "Appendix <X>".

I have more thoughts, but for the sake of not writing a novel in this comment, I will save them for after your response. What do you think?

**Comment by coiko** [comment]
@KianBadie These are fantastic - thanks!  I think they look great.  Sorry for the delayed response, but here are my thoughts on these points:

- I definitely like the grey background bar for the bottom arrows (even without the video/text options).  

- For the profile descriptions, I see the problem with keeping the text and image (especially the landscape-oriented ones) side-by-side.  Maybe for mobile we should have the text appear below the picture.  What do you think?

- For the floating/fixed bar in the landscape view, I agree that the floating (bottom) bar does give more reading space.  And I also agree it should be fixed for the chapter pages (it didn't look too cramped to me).  If it's easier to have it fixed on all pages, that's probably fine, too, since I imagine most users will flip their phone to portrait to read text-heavy pages.

- The titles are great.  I really like the chapter number and title.  For the Appendix, it might be more informative to drop the "Appendix" and include a descriptive title, for instance "A Feature Index".  If the titles are too long, we can use "A Features", "B Scientists" and "C Tree" for short.

I can't wait to hear what else you're thinking about!

**Comment by KianBadie** [comment]
@coiko Thank you, and no worries! 
- Awesome, grey bar it is!
- I think having a single column for profile sections is a fantastic idea! I completely overlooked that option. Would you want the single column even for landscape? I felt like the landscape gave just the minimum amount of space to look ok, and it might stand out if there is a slim profile picture centered on the screen on landscape with empty space around it. Does that last comment make sense? Either way, I guess I we won't know for sure until we try it. So I will show you the results once I play around with it!
- I agree with you, glad the chapter pages weren't too cramped. It won't be hard at all to have fixed/floated on different pages!
- Ah that is a good idea for the appendix pages, I will go ahead and do it that way!

Whatever I was thinking about must have been able to be saved for later because I forgot them! However, I did start development on the section pages! Nothing complete to share yet, but hopefully I can share some concrete milestones soon!

**Comment by coiko** [comment]
@KianBadie Thanks!  And this is great news!  

I think you're probably right that the landscape profile pages will look better with a two-column format, but that's a small detail, so if it's easier to have the same layout in both orientations, just go ahead and make it one-column.

**Comment by KianBadie** [comment]
@coiko Will do with the single column format for both options if having both seems to be difficult. Thank you! Looking forward to sharing the progress.

**Comment by KianBadie** [comment]
@coiko Just wanted to give an update. Developing for mobile has been interesting. I was able to get a rough version of the functionality we wanted for the section pages. However, what seemed to be the trickiest thing to learn is how to work with screen sizes on mobile browsers (highlighted in the below gifs). Most of the trickiness revolved around the top and bottom nav bars of the mobile browser getting in the way of our nav bars. Will do more research into this to see how minimize this for a nicer user experience.

The gifs below are just to share progress and highlight the scrolling issues I was talking about. These are on real iPhones (I use a service that lets me test the site on real devices!), so pretty sure this is how they would actually look in the current state.  

## Version 1
![Peek 2021-01-19 17-16](https://user-images.githubusercontent.com/18221058/105113906-b559c000-5a7a-11eb-9bd8-d14c7aa80ecf.gif)
## Version 2
![Peek 2021-01-19 17-18](https://user-images.githubusercontent.com/18221058/105113914-b8ed4700-5a7a-11eb-8373-1ac07ac8ec49.gif)

**Comment by coiko** [comment]
This is so cool.  Thanks, @KianBadie!

**Comment by KianBadie** [comment]
@coiko I'm excited to give an update that I was able to get the scrolling to a nice and smooth experience (see below)! I will be continuing development with landscape and the other pages. Just wanted to remind that during development, I am open to any changes. So if you noticed anything that you'd like to change or try out, please let me know!

Fun side note: I tried studying different mobile sites to see how they managed to get a good user experience. The site that finally made things click was reddit's!

## Gif 1
![Peek 2021-01-20 12-47](https://user-images.githubusercontent.com/18221058/105232889-eccd7880-5b1d-11eb-8fae-aee904941983.gif)

**Comment by KianBadie** [comment]
@coiko No problem! 

Ah I hear you. No apologies needed! I am open to doing what's needed to make the website great! Also, changing the order of the text/video in this case won't be a task that requires any backtracking. So no time wasted! Let me know if there is anything I can do to help with that polling (like if you need any mocks or anything).

**Comment by coiko** [comment]
Thanks @KianBadie!  So the verdict is that people read (at least part of) the text before watching the video, so do you mind switching the order at some point?  Again, I'm sorry I didn't think of this earlier!

**Comment by KianBadie** [comment]
@coiko No worries at all! Glad to make it better. Let me know again if anything changes and I'll be happy to work on it.

**Comment by KianBadie** [comment]
@coiko I have another update. I made initial versions of the section pages for landscape, the landing page on landscape + portrait, and the chapter pages on portrait. You can see this in the screenshots/gifs below. The first set of pictures/gifs are when things look nice.

There are some small things I wanted to address:
- The top blue nav bar is smaller than before. It seemed to give the modal on portrait too little space, so I decreased it's size. What do you think?
- The text is pretty big on landscape (in modals/text sections). There is an option to disable that, I just haven't looked too deep into it yet.
- I have not yet implemented putting the text before the video. I started development on the other pages just to give myself a change of scenery. I will implement that soon!

And just a reminder, this is a real iPhone and not a mock. So this is pretty close to how we can expect things to look **so far** (still plan on touching up and continuing development on all these pages). Please let me know if you have any thoughts or comments!

## Text/Video section landscape
![text-video-landscape](https://user-images.githubusercontent.com/18221058/105437463-fb975680-5c15-11eb-8e47-9fb375f3413f.gif)
## Modal
![modal-portrait](https://user-images.githubusercontent.com/18221058/105437539-1ff33300-5c16-11eb-8808-5f0712314d4b.gif)
![modal-landscape](https://user-images.githubusercontent.com/18221058/105437546-22558d00-5c16-11eb-8634-51850ae61ab4.gif)
## Landing Page
![Screenshot from 2021-01-21 18-15-29](https://user-images.githubusercontent.com/18221058/105437610-3ac5a780-5c16-11eb-8138-8be1721faef4.png)
![Screenshot from 2021-01-21 18-15-38](https://user-images.githubusercontent.com/18221058/105437613-3b5e3e00-5c16-11eb-9171-1040112bd798.png)
## Chapter page
![Screenshot from 2021-01-21 18-15-58](https://user-images.githubusercontent.com/18221058/105437639-4618d300-5c16-11eb-9650-9c6406783696.png)

**Comment by KianBadie** [comment]
@coiko As I have started to develop the appendix pages, I have realized that I'm not sure if we decided on a position for the bottom controls bar on landscape for all pages. I know on section pages the controls bar floats to the bottom of the page instead of being fixed at the bottom of the screen. Do we want that on the appendix pages as well? If you need a reference, the mocks from earlier have examples of each to compare.

In my opinion, it should float to the bottom of all pages to give more screen space. What do you think?

**Comment by KianBadie** [comment]
@coiko Also, here is my update before the weekend. Worked on the chapter pages and the feature index/profiles page. In a similar spirit to yesterday, I was hopping around the pages for some new scenery. So the gifs below are all works in progress. For the sake of not flooding this comment thread with images, I took some gifs of my progress "on it's good side". With each of these pages, there are still plenty of bumps to smooth out (like how "text" and "video" are still displayed in the controls bar on these pages, just for one example). 

As always, please let me know of any comments or ideas! Only question I had is about the profiles page. On portrait, would you like the text to be left, centered, or right aligned with the single column profile layout? For now, I used left alignment.

## Chapter Pages
![Screenshot from 2021-01-22 17-45-56](https://user-images.githubusercontent.com/18221058/105565300-08ca4900-5cdb-11eb-9b4c-0021efbee9ba.png)
## Feature Index
![feature](https://user-images.githubusercontent.com/18221058/105565306-0e279380-5cdb-11eb-997d-90f5987f4cd1.gif)
## Profiles Page
![profile](https://user-images.githubusercontent.com/18221058/105565316-14b60b00-5cdb-11eb-9587-eb8cc9be7369.gif)

**Comment by coiko** [comment]
@KianBadie These are beautiful!  Thank you so much!  For your questions, I think your intuition is right on both counts: I like the control bar floating to the bottom in landscape on all the pages (except the chapter heads, where you found it introduces that slight scroll), and I like the left-aligned text in the portrait mode of the Profiles page.  It also looks like you fixed the text size to be 100% in landscape, which looks great!

**Comment by KianBadie** [comment]
@coiko No problem, I'm glad you like them! Does the exception of the floating bar to the bottom also include the video pages in addition to chapter heads? Or did we decide it wouldn't be like that? And got it, left aligned it is!

I'm not sure what is causing the text to not increase in size here yet, but I'm surprised it didn't get larger! Either way, I will be implementing something to have the text be guaranteed consistent for all pages!

**Comment by coiko** [comment]
Thanks @KianBadie!  And yes, of course you're right - also the video pages!

**Comment by KianBadie** [comment]
@coiko Just checking in and reassuring that I'm still on this issue! Not much of a visual update for the past two days. Since I showed the previous pages at their "good angles", I've just been refactoring/restructuring things in order to work out the "bad angles" as well as make it easier in general to finish the mobile implementation. Hopefully I will have more to show soon.

**Comment by KianBadie** [comment]
@coiko In a similar position as yesterday. Trying to refactor code to make things easier, checking more how things look on android, and trying to smooth out quircks I can that come with mobile. Just to show something though, I wanted to share some progress that show some quircks and good angles on an actual android phone! Still aiming to have something satisfying this Friday in regards to how the whole site looks on mobile.

## Gif
![progress](https://user-images.githubusercontent.com/18221058/106080599-41e42e00-60cc-11eb-8842-7ebfac7c7fa1.gif)
## Nav
![Screenshot from 2021-01-27 18-15-56](https://user-images.githubusercontent.com/18221058/106080608-47417880-60cc-11eb-9e34-8d6b382df40c.png)

**Comment by KianBadie** [comment]
@coiko I still have been moving forward with development and not too many issues are coming up. I'm still going through the smaller issues/tasks related to the mobile development. So everything pretty much looks the same (with some minor changes to things like font-sizes or minor icon replacements for example). I do have something I wanted to run by you, since it is a little bit more open ended than the stuff we have previously talked about before.

I put the footer information in the nav menu (screenshot below). What are your thoughts on it? It's very minimal, but I wanted to see if it was missing something for you. Also, while we are here, how do you feel about the nav bar covering the bottom controls (it currently ends right before them)? It would have more space, but obviously block the controls. Part of me feels like the nav menu looks a bit cramped and it would be worth it to cover the controls for more space.

## Footer information
![Screenshot from 2021-01-28 13-40-01](https://user-images.githubusercontent.com/18221058/106202171-61339780-616e-11eb-95f3-f05936e68a2b.png)

**Comment by coiko** [comment]
@KianBadie I love it!  It looks great.  My only thought is that maybe we should use something shorter for the last item - something like "© 2020 Caltech Library".  What do you think?

I also like your idea of having the nav menu cover the bottom controls.  I think it will look better that way, and the extra space will be very helpful.  Also, what do you think about having it cover at least part of the top bar as well?

**Comment by KianBadie** [comment]
@coiko I think that shorter field is a great idea! I'm all for it.

Awesome, I will change it to that then! I personally think having it below the top bar is good, one functional reason being that the nav button can be pressed again to close the menu. What do you think? I could explore it more and show some screenshots! It will be a quick thing to test out to see how it looks.

**Comment by coiko** [comment]
@KianBadie Awesome!  That makes perfect sense.

**Comment by KianBadie** [comment]
@coiko Looking forward to catching you up on all the progress during tomorrow's meeting! In the meantime (feel free to save responses for tomorrow if you'd like) I have some examples for you to check out with having the nav menu cover the top header.

## Portrait
![portrait](https://user-images.githubusercontent.com/18221058/106221598-c5685280-6192-11eb-8a09-d7f9abc37766.gif)
## Landscape
![landscape](https://user-images.githubusercontent.com/18221058/106221603-c8634300-6192-11eb-8caf-e5c41bb9c92b.gif)

**Comment by KianBadie** [comment]
The first iteration of the mobile layout is available to view on the [GH pages url](https://caltechlibrary.github.io/cell-atlas/) for this site. Currently, schematics and summary videos are not available to view for reasons outside of the mobile implementation, but everything else should work as normal. Please feel free to give any feedback whatsoever!

**Comment by coiko** [comment]
@KianBadie Thanks so much!  This is looking fantastic!  I really love the layouts of all the pages.

Here are my thoughts from testing it on Android (a Pixel 3 XL):

- the video behavior is a little wonky if you start from portrait orientation. It automatically expands and goes into landscape, but when you flip the phone to view it, the orientation sensor kicks off a behavior where it stops the video and shrinks back to the un-expanded view, flips back to (now sideways) portrait mode, and finally back to landscape, at which point you have to start the video again.  It might be hard to understand from this description, so let me know if it would be better to show by video.
- would it be better to reverse the brightness of the Text/Video selection?  Currently, the selected one is bright, and the other dim, which makes sense.  But intuitively, I found myself wanting to click on the bright one, so it might be a better nudge for people to go on to the video by having that brighter (when you're on the initial text default).  What do you think?
- if it would be easy, it might be nice to have a minimal scroll indicator in the drop-down nav menu.  Depending on the size of the device, it can look like the menu ends at the bottom of the phone, so a thin bar on the side might help people realize they can scroll down to see the rest (Appendix, About, etc.).
- I think it will be fun to try icons for the Text/Video options at the bottom.  Maybe something like these ([text](https://fontawesome.com/icons/file-alt?style=solid) / [video](https://fontawesome.com/icons/video?style=solid))?

**Comment by KianBadie** [comment]
@coiko Glad they are looking good! Thank you for the feedback as well. In regards to your points:
- Ah I see. That is wonky behavior indeed. I think I understood what is happening through your description, but I think a video would still help (if not too inconvenient to record. Does android have screen capture built in? If not, we can try to find another way to share). Unfortunately I wasn't able to replicate that bug with a Pixel 3 XL through the service I use. They're real devices on the service, but still not the full experience of actually controlling the physical/personal device of course, so they could be missing that "real life" behavior that you are experiencing. Which browser was it on?
- That is funny, I actually initially had the button brightness the way you described but I decided to reverse it, as the current way felt more natural to me! It might just be my preference however, so we could switch it and see how it feels. I'll try to poll around as well and see what others think.
- Ah I see, yes that could be a good idea. Yeah I would be happy to try to implement that!
- Those icons look great! I think it would be fun to see how they look in the site and I will happily look into that as well.

**Comment by KianBadie** [comment]
@coiko This weekend I attempted to replicate that orientation change bug in person on a Samsung Galaxy J7 and another Samsung Galaxy model. I was not able to replicate that specific bug. I would click the play button and I would change the orientation of the phone and it would continue playing. Even if I flipped it upside down, the video would flip and continue to play.

This is both good and bad news. It's great that the bug isn't happening on all devices! But also unfortunate that the bug is mysteriously happening on certain devices and is inconsistent. I'll try to get my hands on more android devices to check the experience. If it is a Google Pixel specific bug, that would be quite strange. In the meantime, is there any convenient for you to check on any other android devices accessible to you? Hopefully, checking on different android devices could help us narrow down what the "requirements" of the bug are.

**Comment by KianBadie** [comment]
@coiko Here is a go at implementing icons in the controls bar. What do you think? I tried to keep the controls bar the same height. If you think it could use some more space. Please let me know.

## Icons only
![icons_only](https://user-images.githubusercontent.com/18221058/108009831-5d01d980-6fb8-11eb-944c-84885a620f34.gif)
## Icons with text
![icons_text](https://user-images.githubusercontent.com/18221058/108009855-68550500-6fb8-11eb-8769-6660f6216ff6.gif)

**Comment by coiko** [comment]
@KianBadie It's beautiful!  It looks fantastic.  I (and my poll of 1 other person) like the icons-only version slightly better, since they're so nice and clear.  Also, I think I realized why the brighter-selected option was counterintuitive to me.  I think it's because the (unselected) arrows are also bright.  If you agree and it's easy, could you try making them dimmer, too?

**Comment by coiko** [comment]
@KianBadie Also, thanks for looking into the orientation issue!  Unfortunately, I don't have any other Android devices at hand, but I did figure out that it only happens if the "auto-rotate" setting on the phone is activated.  So maybe that's why the testing devices didn't replicate the behavior?  Anyway, it's a very minor issue, so feel free to leave it.

**Comment by KianBadie** [comment]
@coiko Awesome, icons only it is! Yeah I would love to try that. I will post screenshots of that soon.

I believe I had auto rotate on when I tested on both devices, but I will double check just to make sure!

**Comment by KianBadie** [comment]
@coiko Here is how things look for the different icon shading options! I also took a poll of 1 other person and they found that the "bright = selected" style was intuitive for the icons. 

## Nav buttons dimmer
![navDim_shadeNorm](https://user-images.githubusercontent.com/18221058/108104617-633b9880-7040-11eb-8f8a-62814e70b7a1.gif)
## Nav buttons dimmer, button shading reversed
![navDim_shadeReverse](https://user-images.githubusercontent.com/18221058/108104633-69ca1000-7040-11eb-89c7-7888fdada0e4.gif)
## Nav buttons current brightness, button shading reversed
![navNorm_shadeReverse](https://user-images.githubusercontent.com/18221058/108104656-70588780-7040-11eb-91d0-598b8722087e.gif)

**Comment by coiko** [comment]
Thanks so much @KianBadie!  The first option (bright=selected, nav buttons dimmer) looks perfect to me!

**Comment by KianBadie** [comment]
@coiko I had 2 quick questions I wanted to run by you in regards to the mobile site:
1. All links to the download page are removed on smaller screen sizes. However, the page is still accessible if you type the right link. Would you want to provide some sort of heads up message for those mobile users that end up at the download page? Something to warn of the non-friendly user experience of accessing the downloaded the files on mobile? In addition, screen size might be a tricky thing to determine download availability (I guess small desktops are possible and it seems large devices like tablets use a mobile like OS). Would you want larger devices like tablets to also be treated like small screen mobile devices (remove links to download page)? If so, I can change the code to try to check the OS rather than depend on the screen size for this specific issue. 
2. I have been looking into forcing the scroll bar to display in the nav menu. Surprisingly, it is another topic with more than meets the eye. Android (at least on Chrome) allows what we want easily. However, from my research so far, iOS 13+ has prevented custom scroll bars from showing (showing the scroll bar requires removing the default style and creating a new custom style). Having the scrollbar always show on iOS 13+ would require recreating the scroll bar from scratch (not impossible, but I'm not entirely sure how the result would turn out). I think that brings us to these options. Try out recreating the scroll bar, Have the scroll bar show on devices that support it (Android) and let iOS do its own thing, use another minimal scroll indicator (a down arrow or a shadow at the bottom when there is more content), or sticking with iOS/Android default design (scroll only shows on interaction). I have seen different opinions about user experience and scroll bars (I might have gone a little too deep down the rabbit hole for a small topic), and it varies. My personal opinion right now would be to either stick with the default design or a another minimal scroll indicator for feasibility reasons and slightly to stay conformed with iOS/Android default design (I think the another minimal scroll indicator would still fall into that conformity). What do you think?

**Comment by coiko** [comment]
@KianBadie Good questions.  For 1, it seems like checking the OS as a proxy for device type (mobile/tablet vs. laptop/desktop) makes more sense than going by screen size.  But if that's harder, don't worry about it.

And for 2, I say definitely don't worry about it and leave it with the default design.  It seems like a better option long-term to use the built-in styles rather than forcing something else.  Of course, if you're enjoying the rabbit hole, feel free to try one of the minimal indicators you mentioned, but otherwise it might be more fun to explore some new ones!

**Comment by KianBadie** [comment]
@coiko Sounds good! For the detecting the device type, would you like to display any sort of message or prevent any sort of downloading for applicable devices? Preventing seems like it might do more harm than good, but do you think a heads up message for mobile device users on the download page would have value? Something like "The offline version is most accesible on a desktop operating system..."? Currently, mobile devices will just loose links to the download page, but still have access if they type in the url.

Also, I tried to replicate the orientation bug in person again on a Samsung Galaxy 9 with auto rotate on and off and experienced some interesting behavior. One thing I noticed was that sometimes the video would enter full screen and try to play in landscape, but because I was still holding the phone in portrait it would flip back to portrait and stop playing because it is no longer in full screen. This made me feel like I wasn't flipping "fast enough", which I think is obviously not the best user experience. What's interesting though is that this happened to what felt like half to a quarter of the time. I would try to replicate it by playing the video while keeping the phone in portrait, but thankfully it would work as expected half of the time. Interesting stuff, and definitely want to solve it in the near future. Maybe what I described might be similar to the bug you were experiencing.

**Comment by coiko** [comment]
@KianBadie Sorry for the delayed response, and for forgetting to answer this in my last comment (which I realized as I was falling asleep last night)! I do like the idea of a message on the download page.  How about adding it into the first sentence so it would read "If you'd like to download this digital book to read offline (not recommended for mobile devices), choose one of the options below."?

And as for the orientation issue, that does sound like it might be the same bug.  I also don't get it every time, but it happens at least 95% of the time on the Pixel 3 XL and it doesn't seem to matter if I flip immediately or wait a bit, so maybe it's device-specific.  Also remember you discovered that funny feature where if you flip it to the other landscape side so it's playing upside down, it reorients and keeps playing just fine without the stopping/going-back-to-portrait.  Weird stuff.  Anyway, it sounds like it might be a niche bug, and it doesn't really interfere with the UX (you get trained to flip the phone before hitting play pretty quickly) so I wouldn't spend too much energy trying to figure it out.

**Comment by KianBadie** [comment]
@coiko No worries at all! Yes, I think that is a great message! I will add that.

Weird stuff indeed! You're right, I will put this bug down for a little bit and pick it up again for another round some time later. In the meantime, I took today to polish up anything outstanding and here are some screenshots of some things I touched up today. My apologies for the delay. I told myself that tomorrow will be the day that I call it a wrap for now before the re-release. One thing that I realized is that there wasn't a period this time for you to preview things before merging into the main site. Would you like to have some time previewing the site on the main branch before merging into the main one?

## iPhone notch (before/after)
![iphone_notch](https://user-images.githubusercontent.com/18221058/108294757-5192e780-714b-11eb-9d26-6749f73a152a.gif)
![iphone_notch_improve](https://user-images.githubusercontent.com/18221058/108294752-4fc92400-714b-11eb-9720-763b189abe9c.gif)

**Comment by coiko** [comment]
@KianBadie Beautiful!  Thanks so much for cleaning these things up.  It looks really good!  As for previewing, I'd love to take a quick look at it before you do the official merge, but I certainly don't need more than, say, half an hour.  I have some meetings tomorrow morning, but I'll be free for the rest of the day, so just let me know whenever you want a fresh set of eyes (and an Android device) to give it a quick once-over.  And please don't worry if anything comes up and it takes longer - we're not under any hard deadline this time!

**Comment by KianBadie** [comment]
@coiko Thank you so much for the patience! I will do one more look through myself and I will let you know when it is ready for a fresh set of eyes.

**Comment by KianBadie** [comment]
@coiko The notch currently covers some of the modal windows, but I concluded it was minor enough to revisit at a later time and allow this to go through with the re release of the site.

## Screenshots
![Screenshot from 2021-02-18 11-18-39](https://user-images.githubusercontent.com/18221058/108417859-5a37fc00-71e5-11eb-8328-f2ece04682f2.png)
![Screenshot from 2021-02-18 11-19-21](https://user-images.githubusercontent.com/18221058/108417872-5e641980-71e5-11eb-9def-5456e706e5f4.png)

**Comment by KianBadie** [comment]
@coiko Putting this here to avoid creating a new issue. I should close these issues and start using issues properly, instead of treating them like open forums. But until then, I will detail this here. The fixes to the profile page are merged, so they should be available soon! The anchors should be fixed on mobile, and there should not be an instance where the profile description is cut off. This part does not effect mobile, but there was a bug where the profile description would sometimes sit right up against the scroll bars instead of having some nice hover space. That bug is now fixed too. You might have not seen it since Mac hides their scrollbars and has a hover like style to them. Windows scrollbars are very apparent and take up space.

In our meeting today, I mentioned how the iOS landing position would happen above the profile names, so it would show about 2 names extra. This would happen in landscape. I tested another site's anchors (the test page was a page from the [HTML specification](https://html.spec.whatwg.org/multipage/text-level-semantics.html)) and saw that the same was happening to them. On landscape, there was some extra space above the landing destination. I thought this happened on older versions of iOS, but this was also happening on newer version. Because of that, I think it is a normal thing with iOS and merged the changes.

Please let me know if anything comes up!

**Comment by coiko** [comment]
Thanks @KianBadie!  That sounds great, and the iOS anchor behavior makes sense.  And I had noticed the bug with the missing padding between the text and the scroll bar (but figured it was minor), so I'm so glad you fixed that!

(And for the record, I think this is a fine place for this discussion.)
