### ISSUE TITLE
Modal/Protein Viewer refactoring

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#26]
Refactoring modals/protein viewer to conform to new coding style used to refactor media viewer elements/main section components.

**Comment by KianBadie** [comment]
@coiko I merged the changes for the modal/protein viewer update! Like I mentioned in our meeting, all of the major characteristics of the modals/protein viewers are the same and I will be happy to fix whatever functionality was lost or bugs introduced that we find.

Some characteristics changed however that I wanted to mention:
- I changed the max width of the modal to just be a constant ratio of the screen height. Earlier we were doing some more detailed calculation on how to scale the width of the modal. The fixed ratio is easier, but it does change how things look slightly. I added a screenshot to highlight the difference. Please let me know if you prefer the old width better!
- The protein viewer minimize button on mobile is now on the bottom right (like the videos/comparison sliders). Sometimes there is overlap on mobile portrait when the protein label is really long, but the minimize button will always appear on top. Is that ok with you?

## Before
![modal-pre-update](https://user-images.githubusercontent.com/18221058/139486872-f8e92602-bbfc-4298-b007-522019087335.PNG)
## After
![modal-update](https://user-images.githubusercontent.com/18221058/139486887-0a25544a-6de4-4f19-aa7e-3ec21d42d68a.PNG)

**Comment by coiko** [comment]
Yes and yes!  Both changes are great.  Thanks @KianBadie!

**Comment by KianBadie** [comment]
@coiko No problem! Just in case you tried to check earlier, there was a naming issue with the file names that prevented the modals from working at all on the test site. I just pushed some changes to fix that!

**Comment by coiko** [comment]
Thanks @KianBadie!  They look great for me now.
