### ISSUE TITLE
Exit mobile search when clear input button is clicked

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#28]
On mobile, add functionality to exit search feature when native clear input button is clicked.

**Comment by KianBadie** [comment]
@coiko As usual, it looks like there are some details that make implementing this feature a little less straightforward than initially thought.

The "x" button is a special browser element that is only in Chrome/Safari. Unfortunately, it is not programmatically targetable which means there is no way of knowing when it is specifically clicked. Another more minor point is that the button disappears when there is no text in the search box. So a user would still have tap in empty space to remove the search button. Lastly, I am not sure the accessibility implications of this. I wonder if a screen reader will announce that button as a "clear search" button, but then the search feature is closed when clicked.

I still think this is a good feature to have though. After looking at some search boxes online (youtube, imdb, letterboxd, gamespot, and ign to name some), I saw 2 possible solutions:
- create our own exit search button that could be to the right of the search bar (this is what youtube does, except it is on the left). This allows us to keep that convenient "clear search" button while also adding a way to conveniently exit search.
- remove built in "clear search" button and replace it with our own exit search button (imdb does exactly this). This removes that convenient clear search feature, but keeps the design simple since we still have 1 button in total. Unfortunately, for consistency we would have to remove the clear search button on desktop as well, but it looks like other sites already have that removed (imdb, letterboxd, and gamespot)

Personally, my vote goes for the second option. The built in "clear search" button is not even standard (not existent on firefox), so I think it is ok to remove. In addition, the 2nd option is just cleaner visually in my opinion. A user might incorrectly click it at first thinking it is a "clear search" button, but I think that is a small price to pay. What do you think?

**Comment by coiko** [comment]
@KianBadie Thanks for looking into this (and sorry it wasn't more straightforward)!  I agree that the second option sounds more optimal (cleaner, and less chance of confusion).

**Comment by KianBadie** [comment]
@coiko No worries, all part of the process! Sounds good. It isn't terribly complicated to implement, so I plan on having that merged into the testing site soon.

**Comment by coiko** [comment]
Wonderful - thanks @KianBadie!

**Comment by KianBadie** [comment]
@coiko I just pushed the update to the site for this functionality!
