### ISSUE TITLE
Offline/PWA Features

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#3]
Adding PWA features and offline options for the site. 

### Action Items
- [ ] Research what making the Cell Atlas site into a PWA brings in terms of features.

**Comment by KianBadie** [comment]
@coiko I made an initial version of the download page and the links to the page (from the landing page, nav menu, and about page). Do you have any changes that you think I should add to these initial versions? Some small changes I think would be good are:
- Download icons for the buttons. But like the mobile icons, I need to look into licensing. The licenses for the free icons I have seen require that you include the same license in the code. I will look into that today!
- I feel that the link to the download page from the landing page could use some style changes, but I'm not sure exactly what yet. Do you have any suggestions?
- I put some initial text for the entry on the about page. Would you prefer different wording? Or were you imagining a different way linking the download page from the about page?

## Download page
![download](https://user-images.githubusercontent.com/18221058/107432170-684a9600-6adc-11eb-8953-b9ac762cdaf3.png)
## Link on landing page
![landing](https://user-images.githubusercontent.com/18221058/107432175-6a145980-6adc-11eb-8adf-f3eb730aec4f.png)
## Link from nav menu
![nav](https://user-images.githubusercontent.com/18221058/107432181-6bde1d00-6adc-11eb-9957-f51af1f76490.png)
## Link on about page
![about](https://user-images.githubusercontent.com/18221058/107432184-6da7e080-6adc-11eb-8de7-3a2d6b9de164.png)

**Comment by tmorrell** [comment]
The Noun project has a lot of nice icons that you can use for free as long as you provide attribution https://thenounproject.com/. Example attribution at the end of this readme https://github.com/caltechlibrary/dibs/blob/main/README.md

**Comment by KianBadie** [comment]
@tmorrell It is good to see your response as you were just the person I was going to email to ask! Thank you for the resources

**Comment by coiko** [comment]
@KianBadie These are awesome!  They really look great.  A few ideas for very minor tweaks:
- On the landing page, I agree that an icon would be great.  We could also try minimizing it a bit visually since it will be a less-used option.  It might look nice just as a white cloud/download icon, without the button background.
- On the About this Book page, I'd add "page" after Download in the link.
- In the Nav menu, maybe we should call it "Offline Version" to make it clearer that it's not e.g. an app that we want everyone to download.  I might also put a bit more space (~1 text line) between it and the divider line and make it a slightly lighter grey color to set it apart from the contents above.

What do you think?

**Comment by KianBadie** [comment]
@coiko Great! And I think all your comments sound good and I will go ahead and implement those and circle back when it's finished!

**Comment by KianBadie** [comment]
@coiko Here are the updates! For the landing page, I could add some more style if needed. Maybe a white background with low opacity when you hover over the button like the mock up? Also, please let me know if I should still add some more touch ups (more spacing, different styles, anything).

## Landing page
![Screenshot from 2021-02-10 19-47-00](https://user-images.githubusercontent.com/18221058/107600534-e7bd8f80-6bd8-11eb-9b67-c0cef4ba1b87.png)
## Nav menu
![Screenshot from 2021-02-10 19-47-17](https://user-images.githubusercontent.com/18221058/107600532-e724f900-6bd8-11eb-838e-78a079de7415.png)
## Mock Up
![Screenshot from 2021-02-10 19-58-49](https://user-images.githubusercontent.com/18221058/107601055-6b2bb080-6bda-11eb-9a78-cfdcdec2c419.png)

**Comment by coiko** [comment]
@KianBadie These look awesome!  I love the icon.  I do kind of like the low-opacity button background, if you don't mind trying it?  I'd probably have it at all times, rather than just on hover.  And for the mobile version, I think we could just have the icon without the text.  What do you think?

**Comment by KianBadie** [comment]
@coiko I think those are great ideas to try! I will go ahead and incorporate those.

**Comment by KianBadie** [comment]
@coiko Here is the button with the new styling. I checked out how opening the downloaded files on mobile worked out. Unfortunately, it is a lesser user experience when compared to using an actual laptop/desktop. On iOS, it didn't seem like I could open the files in the browser. I could view the files within the iOS files application. However, any external files to the one being viewed were not accessible (video and image files for example). To view those, I had to browse the file app to those videos/images and I could view them in isolation. With android, I could open up the files in a browser, but the same story would happen where external dependencies were not accessible. It doesn't seem like browsers can access local files on mobile like they do on desktop.

My thoughts are to leave the download option to desktops only for now and circle back to this later if desired. I think the user experience was a little disappointing to what an expected download would be on a mobile device, and I think it would be an overall better user experience if one just didn't see the option on mobile. I tried researching more about this and did not find any promising leads. I think a lot of the features related to offline have had a lower output of features to time spent ratio, and I wouldn't want this topic to become a choke point in the overall development of this site. What do you think? 

## Desktop
![Screenshot from 2021-02-11 13-01-30](https://user-images.githubusercontent.com/18221058/107698374-4d595c80-6c69-11eb-9dfa-a38c5a9ed6fc.png)
## Mobile
![Screenshot from 2021-02-11 13-01-17](https://user-images.githubusercontent.com/18221058/107698372-4c282f80-6c69-11eb-8422-8471fe2223f6.png)

**Comment by tmorrell** [comment]
I second removing the download on mobile for now. You'd want to structure the download as more of an application bundle, which is feasible but more work than the current download for desktop.

**Comment by coiko** [comment]
@KianBadie I'm so sorry!  I totally blanked (again).  Of course we shouldn't have the download option on mobile.  So sorry about that.

And yes, I think the download icon styling is perfect now.  Thanks!

**Comment by KianBadie** [comment]
@coiko no worries! I was curios how it would turn out and wanted to give a short try with it as an experiment. I will go ahead and hide the download icons/links for mobile.

**Comment by KianBadie** [comment]
@coiko So it looks like the zip file references all of the offline videos correctly. The black bars on the top and the bottom of the videos have an interesting affect that make the videos taller. Making the videos shorter would decrease the width of the video to keep the same aspect ratio. The section videos look ok on my machine. However, on Windows and Mac, the videos become to tall to access the controls when the text is shelved. Regardless of the video height, videos being too tall were a problem (not as tall as this, however) and that will be something to add to my polish list by next mid-week. With these videos, would you prefer I try to change the styling to make them shorter, or is there a convenient way to export the videos without those black bars to save space?

## Section
![Screenshot from 2021-02-12 13-48-26](https://user-images.githubusercontent.com/18221058/107826150-3b46ef00-6d39-11eb-89ed-15da3596c1fc.png) 
## Sections to same height as 1080p videos
![Screenshot from 2021-02-12 13-56-01](https://user-images.githubusercontent.com/18221058/107826660-1a32ce00-6d3a-11eb-8823-8a13c8bfcb89.png)
## "More" videos
![Screenshot from 2021-02-12 13-58-16](https://user-images.githubusercontent.com/18221058/107826815-641bb400-6d3a-11eb-8a4d-5084452896b9.png)
## "More" videos shorter
![Screenshot from 2021-02-12 14-00-55](https://user-images.githubusercontent.com/18221058/107827018-c8d70e80-6d3a-11eb-8d0e-bb299cadedec.png)
## Sections Safari
![mac_safri](https://user-images.githubusercontent.com/18221058/107827673-26b82600-6d3c-11eb-9050-cef272c590b8.gif)
## Modal Safari
![Screenshot from 2021-02-12 14-09-36](https://user-images.githubusercontent.com/18221058/107827694-359ed880-6d3c-11eb-91e3-cd84e2780275.png)

**Comment by coiko** [comment]
@KianBadie Thanks for testing this!  I definitely think the solution is to render them without the black bars.  There's an odd quirk of the software I use that introduces a distortion with the 480p "wide" format, but not the 480p (with the black bars), so I was lazily using the 480p version.  But I figured out a workaround today and I'm re-rendering them all.  I'll send along the new files (along with the 480p versions of the schematic and summary videos) as soon as I finish (probably Monday).

**Comment by KianBadie** [comment]
@coiko No problem! Great to hear there is a workaround. I agree that taking out the black bars is better visually compared to the other option. Monday sounds good! Thank you very much for doing that. On the bright side, one good thing that came out of this is that it made me want to handle that video height issue that these black bars highlighted. So hopefully that won't be an issue in the future.

**Comment by KianBadie** [comment]
@coiko For the downloadable files, the feedback form is currently available. It will display properly if there is an internet connection available and will display like the screenshot below if there is not. Would you prefer to display something else if there is no internet? Or are you fine with this displaying? There is no way of interacting with this "disconnected" version of the form, it is a just a picture of the form at this point.

## Screenshot
![Screenshot from 2021-02-16 13-08-57](https://user-images.githubusercontent.com/18221058/108121861-490db480-7058-11eb-99b5-8ed6d23d1a5c.png)

**Comment by coiko** [comment]
@KianBadie Thanks for catching this!  If it's easy, my preference would be to instead display a message like "Please connect to the internet to provide feedback."  If it's not ridiculously easy, though, I'd just leave it.  It doesn't do any harm.

**Comment by KianBadie** [comment]
@coiko Here is the very simple display of what the form looks like with no network connection. If a user is connected to a network that does not have working internet, the previous wonky feedback form from the screenshot above will show. The below screenshot only shows when a user is not connected at all to a network. Not ideal, but I figured it was good enough to make do for now. Does this also look ok to you? Or do you have different thoughts? 

## Screenshot
![Screenshot from 2021-02-18 11-41-07](https://user-images.githubusercontent.com/18221058/108418205-c6b2fb00-71e5-11eb-890b-851f79fbf8d8.png)

**Comment by coiko** [comment]
@KianBadie Looks perfect!  (And yes, the other display for the unlikely case of connection with no internet is just fine.) 
 Thanks!

**Comment by KianBadie** [comment]
@coiko I forgot if you sent a picture of the new look for the download button. But was it something like this?

## Screenshot
![Screenshot from 2021-03-12 16-17-05](https://user-images.githubusercontent.com/18221058/111011535-9a0a8300-834e-11eb-9205-7d3005db7d25.png)

**Comment by coiko** [comment]
@KianBadie You have a fantastic memory.  That looks great!  To be super fiddly, could you try moving it down a little farther (~twice the current space from the Read Online Now button) and making it a little (maybe 30%) smaller?

**Comment by KianBadie** [comment]
@coiko How does this look? Also, as of right now the block of text (title, authors, description, button, and link) are all vertically centered. So adding the new link raised everything up a bit. I know it's small, but please let me know if you prefer everything to be lowered to it's original height!

![Screenshot from 2021-03-12 16-56-37](https://user-images.githubusercontent.com/18221058/111013381-fcb24d80-8353-11eb-86bf-af66616416ba.png)

**Comment by coiko** [comment]
@KianBadie It's fantastic!  I actually like the raised main block.  (I also like the centered arrow!)  I'm tempted to make the download text even smaller, similar to the font size in the footer.  What do you think?

**Comment by KianBadie** [comment]
@coiko Great! That makes things easier. Here is what it looks like with the font the same size as the footer. Personally, I like it the previous size as the smaller size seems a bit too unnoticeable. But I'll leave it to your call, since I have a bias!

![Screenshot from 2021-03-12 18-00-14](https://user-images.githubusercontent.com/18221058/111015279-d3e28600-835c-11eb-9d91-1d74c800de0b.png)

**Comment by coiko** [comment]
@KianBadie Absolutely - let's go with the previous size (but thanks for checking)!
