### ISSUE TITLE
Summary Menu Refactor

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#31]
Refactor summary menu to implement new media viewer widget.

**Comment by KianBadie** [comment]
@coiko I just pushed a summary menu update to the testing site. Other than improvements behind the scenes, I did get a chance to greatly improve the pan/zoom functionality of the summary menu. Now you can pan and zoom in a much more streamlined way. In addition, pinch zooming has much less hiccups than it did before. In the past, pinch zooming would "snag" and stop zooming in/out at random points. It is a lot smoother now.

If you want to see the full extent of the zoom differences, you can compare the menu to the main site! Unfortunately I can't post gifs since I need an actual touch device to display the actions. There is still room for improvements on the zooming functionality, but I believe this improvement warranted a merge.

**Comment by coiko** [comment]
It looks great!  Thanks so much @KianBadie!

**Comment by KianBadie** [comment]
@coiko One last thing I wanted to quickly improve for the summary menu was its accessibility. Currently, if you tab through the summary menu with a keyboard you have to "activate" the menu part in order to get the text to show. I was thinking of changing this to automatically show when keyboard focused is received (rather than activating it). It seems like it might more accessible if one could tab through the menu and have the contents be automatically revealed (to something like a screen reader) without the need for further input. Would this be ok with you?

**Comment by coiko** [comment]
@KianBadie That sounds like a great idea!  Thanks!

**Comment by KianBadie** [comment]
@coiko Great! I merged those changes into the site!
