### ISSUE TITLE
Update page metadata

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#35]
Update metadata in `<head>`. This issue is a small piece of the overall effort to improve SEO and accessibility.

**Comment by KianBadie** [comment]
@coiko One piece of improving SEO is to optimize the metadata of the document. I wanted to start with page titles (the titles that show in search results/in the window tab. Not the actual titles that appear within the web page). Page titles looks like they mostly benefit how search results look and page accessibility rather than how they rank, but I thought I would might as well get it out of the way since it felt like a good starting point (before investigating if other metadata can be improved to affect ranking).

Our page titles for sections look pretty good for the most part with the "`<section name>` | Atlas of Bacterial and Archaeal Cell Structure". I was thinking of making the homepage just "The Atlas of Bacterial and Archaeal Cell Structure" and removing the section letter name from appendix pages (converting "B Scientist Profiles | Atlas of Bacterial and Archaeal Cell Structure" to "Scientist Profiles | Atlas of Bacterial and Archaeal Cell Structure" since the "B" wouldn't provide much information in a search result or screen reader). What do you think?

**Comment by coiko** [comment]
Thanks @KianBadie!  I think that sounds perfect!

**Comment by KianBadie** [comment]
@coiko After some more research, it looks like the last meaningful thing we can change in this type of page metadata is description. Unfortunately, it also does not affect page ranking but can possibly be displayed as the description in search results if google feels it better matches a query than the page content. Because of that, it is recommended to have good descriptions.

Right now, the description for each page "A visual tour of the microbial cell." You might have not seen this before since google usually displays our content instead of the description tag. If you would like to have a unique description for each page, we could try to generate a snippet that captures an essence of the page, or even some keywords that are related to the page. I thought of something like "Written by `author`, information and media relating to `page title` and `species name`." It's a bit rough, and in the grand scheme of things I think google's auto-generated snippet will be more important. I think it doesn't hurt to try to generate something easy though. What do you think?

**Comment by coiko** [comment]
@KianBadie Sorry for the late response!  I like the idea of making more tailored page descriptions!  (Although I agree that displaying the content itself, as happens now, will usually be better.) Maybe something like "Microbiology textbook entry about [page title] highlighting [species name]." It's a little awkward for the titles in Chapter 3 (e.g. "Rod" or "Square") but everything else should work pretty well.  What do you think?

**Comment by KianBadie** [comment]
@coiko Sorry for the late response myself! I wanted to look into a few more things about SEO before taking more action on the topic. I think it is definitely an improvement, and I am happy to go with that. If we have any new ideas in the future, it will be an easy thing to change.

To clarify what I said earlier about results displaying the content itself: I think google will choose whatever is the best match. So the description can be a good place to bring together relevant content that might be scattered around the main content. That summarized and concentrated content might match a query just right depending on the query! I think putting the page title and species name is a step in that direction.

**Comment by KianBadie** [comment]
@coiko One thing I just realized is that the description "formula" we have created does not work as well with non-section pages. For now, I am using:
- "Microbiology textbook introductory page to chapter [chapter] [chapter name]" for chapters 
- "Microbiology textbook appendix page about [title]" for appendix pages
- "A visual tour of the microbial cell" for the landing page

However, that still leaves the introduction chapter page, about, and download page with clunky titles since they don't have chapters to them. Since the bulk of the pages are generating their own descriptions, how do you feel about writing tailored descriptions for a couple of pages? We can have a "use preferred description if it exists, generate it if it does not" system. What do you think? The about, download, and introduction chapter pages could have some simple descriptions.

**Comment by coiko** [comment]
Thanks @KianBadie!  That sounds great.  I'm happy to write those.  Would it be better to write a short tailored description for all the pages?  If so, it's easy for me to do that.  Just let me know.

**Comment by KianBadie** [comment]
@coiko Thank you!

I think writing short descriptions for the rest of the pages would be worth it under certain circumstances. Obviously, one big con is that it will be time consuming. In addition, it seems like it would be most beneficial if the descriptions captured the "scattered" content of the page like the main and modal content. Because if it was just a summarized version of the main section content, I think google already has us covered for that with their auto-snippet generation. It seems like the main benefit of the description is to highlight the page from a different perspective that hits keywords that the content otherwise couldn't capture in a single snippet.

Do you think there is a way to work the modal titles into the description? Something along the lines of "...with supplementary content about [subsection], [subsection], and [subsection]"? If so, we can also include that in our generation.

**Comment by coiko** [comment]
@KianBadie That sounds very doable and very worth it!  And yes, the modal description sounds perfect!  What would be the ideal length for these descriptions?

**Comment by KianBadie** [comment]
@coiko Sounds great! It looks like google cuts things off at around ~160 characters on desktop. In reality though, I think it's more so dependent on overall width (since different characters take up different amounts of space) and the device screen size. If you would like, I found [this preview tool](https://mangools.com/free-seo-tools/serp-simulator) to get an idea of what a description can look like on desktop/mobile.

In addition, [here is a link to google's guidelines](https://developers.google.com/search/docs/advanced/appearance/snippet#meta-descriptions) on best practices for descriptions if you wanted some more in depth explanations of a good description. In general, I think the formula we created is on the right track. I would say the most important thing is just to make sure all the description content is relevant to the page because we might be penalized seo-wise if google thinks it is misleading. But I don't think any of what we have discussed is close to that.

**Comment by coiko** [comment]
Beautiful - thanks so much @KianBadie!  I'll get on these then.

**Comment by KianBadie** [comment]
@coiko I just updated the author-content-changes branch to be up to date with the main testing branch. Whenever you planned on creating the descriptions, you can just add a "description" field to the metadata and push all the changes to that branch!

**Comment by coiko** [comment]
Perfect.  Thanks @KianBadie!
