### ISSUE TITLE
Fixing mobile tap targets

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#37]
Google lighthouse has marked the mobile video citation element as having too small tap targets. It was marking this as a failed criteria in there seo audit. Increasing the size can improve seo by being more mobile friendly on google's terms.

**Comment by KianBadie** [comment]
@coiko As I have described above, it looks like this one small change could have an impact on seo (however small it is). After I modified the padding on the video citation links to how they are in the screenshots below, google gave our SEO rating a 100% for mobile. Of course google's seo audit can't pinpoint the more nuanced parts of seo that have bigger impacts, but if this is a simple "tick mark" that google uses in their ranking system, then I think it might be worth to change it. I will say though, I do not think it looks as sleek as it used to. What do you think?

## Screenshots
![main-portrait](https://user-images.githubusercontent.com/18221058/144337529-cd4b009f-42a5-433a-8669-069586a5dfdd.PNG)
![main-landscape](https://user-images.githubusercontent.com/18221058/144337543-61a82f1a-0486-4099-b62b-552733ca799a.PNG)
![modal-portrait](https://user-images.githubusercontent.com/18221058/144337549-0260a535-e40e-4ffd-a777-fa48dafe42f3.PNG)
![modal-landscape](https://user-images.githubusercontent.com/18221058/144337556-6ebf4f87-5835-452a-a878-961ff3c501c0.PNG)

**Comment by coiko** [comment]
Thanks @KianBadie!  I see what you mean about not being as sleek, but I guess it's worth it for accessibility.  And you can't argue with a 100% rating, right?  Thanks so much for looking into these SEO aspects.

**Comment by KianBadie** [comment]
@coiko No problem! And I agree, it is hard to not be enticed by a 100% rating. Especially from an SEO sense. The inner workings of google rankings are a mystery, but who knows how simple check mark criteria like this boost/hold back rankings.
