### ISSUE TITLE
12/17 Update

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#38]
General issue to cover small points that are related to the upcoming 12/17 update

**Comment by KianBadie** [comment]
@coiko I just pushed some changes to bring the preview banner back to the landing page. I put in some place holder text for now, but please let me know if there is a better preview message you would like to use!

**Comment by KianBadie** [comment]
@coiko In addition, I added a download button for the upcoming pdf version. It just says "Download Edition 2.0 - PDF version". Please let me know if you think there is a better description for it!

**Comment by coiko** [comment]
@KianBadie Oh they look perfect (both the banner and the PDF download button). Thanks so much!  I'll add a brief description to the download page (after the "the full version . . . the light version . . .) when I push text changes to the .md files, but then I think all we need to do is update the buttons to "Edition 2.1" when the time comes.

Also, Grant expects to finish the narration files in time, so we should be able to keep that feature in for this update.

**Comment by KianBadie** [comment]
@coiko How is the video player working for you? I have been running into some hiccups with the service I am using to test on safari. I am not sure if the service just has slow internet at their center, or if the hiccups are real. The hiccups happen when skipping around when seeking. It feels like there is some lag when the mouse let's go of the seek bar before the video resumes playing.

**Comment by coiko** [comment]
@KianBadie Ah, funny!  I see the same thing.  It looks like forward scrubbing (which used to be Safari's forte) isn't working particularly well anymore (whether playing the video or not).  Oddly enough, on Chrome, forward scrubbing now seems to be working much better for me than it used to - not perfectly smooth but pretty close.  I guess it must be something with the browsers?

**Comment by KianBadie** [comment]
@coiko Interesting! Which version of Mac OS do you have? Are you on Safari 15? So far, it looks like Safari 15 has introduced some problematic behavior. Fortunately, I have some fixes in mind for the bugs I found. However, the hiccups with scrubbing on different versions might take some more investigation on my part.

**Comment by coiko** [comment]
@KianBadie I do have Safari 15.0 (on macOS 10.15.7) so that's probably it.  Thanks for looking into it, but don't worry too much - it sounds like something that they're likely to fix from their side in a future version.

**Comment by KianBadie** [comment]
@coiko Ah I see! Yeah I was just in the process of figuring out what is going on with Safari 15. Just to be sure, I am also testing their plain video player by visiting our video urls: https://www.cellstructureatlas.org/videos/1_10_Bbacteriovorus.mp4. If you had the time, could also please also check it out to see that the same bugs exist on that. It would help confirm that the problem really is out of our hands. If it seems any better than our player, please let me know what has improved!

**Comment by coiko** [comment]
Thanks @KianBadie!  Yes, it seems to behave exactly the same way for me, with jerky/laggy scrubbing both when playing and when paused.

**Comment by KianBadie** [comment]
@coiko Strange to say, but that is good to hear! I will continue doing my checks. Please let me know if you notice anything critical with any feature! Thank you for checking that as well.

**Comment by KianBadie** [comment]
@coiko Unfortunately, it looks like orange would be a problematic color for the banner. I attached a gif of the minimum color things would have to be to have good contrast. In this case it was pretty much white (and pretty much black if I went the other way). I also attached an image of an orange banner. The contrast only works if it is black. But like you mentioned earlier, I feel like it is screaming in attention.

We could try making the text bigger. How does that sound? I attached an image of that below as well.

![contrast](https://user-images.githubusercontent.com/18221058/146461815-a326a559-dbf3-476e-bd51-ae70c0d11722.gif)
![orange_banner](https://user-images.githubusercontent.com/18221058/146462070-17733180-65c1-4be2-9c1c-2ac3a65cd6f6.PNG)
![font_size](https://user-images.githubusercontent.com/18221058/146462193-11e9eb15-a714-48c5-9eab-0612cfaf128f.PNG)

**Comment by KianBadie** [comment]
@coiko Also, I fixed the about page. Was a puzzling one, but the problem ended up being that the list needed a "tab" character after each item.

**Comment by coiko** [comment]
Aha - thanks @KianBadie! I'll try to remember that for the future.

Thanks also for trying out the colors.  I agree that the orange background is pretty screamy.  If you're really bored and have nothing else to do, the other thing that occurs to me would be to make the background white to stand out a little more, and then the text either a darker orange (it looks like #C75000 would do the trick), or the site theme blue (#003B4C).  But I'm guessing you're not really bored right now, so feel free to leave it as is (which looks great)!

**Comment by KianBadie** [comment]
@coiko Sounds good! I will let you know if I get to it!

**Comment by KianBadie** [comment]
@coiko I removed the narration announcement from the what's new section and I updated the download page text. I assumed the offline PDF would be under version 2.1, but please let me know if it should be different!

**Comment by coiko** [comment]
Perfect on all counts.  Thanks @KianBadie!
