### ISSUE TITLE
Video player update

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#4]
This issue will cover features related the the video player in section pages

Things to implement:
- [ ] Fix video height bug
- [ ] Video quality control (480p/1080p)

**Comment by KianBadie** [comment]
@coiko I made a fix for the video height. As of right now, a white background fills the extra space when there is no more vertical space available but there is horizontal space available. So if there is a very long but short screen for some reason, there would be a lot of white space on the left and right of the video. However, with the current implementation on the site, the result would be the video filling all the vertical space but also stretching past the header/footer. I wanted to try to avoid the white background filling the extra space, however it was surprisingly finicky and I wanted to make sure I finished other things. So I figured this was already an improvement and to just include it and come back to it. What do you think?

Also, please ignore the visual lag in the gifs. I believe that comes from the service I am using, since I'm remotely testing this.

## With fix
![mac_new](https://user-images.githubusercontent.com/18221058/107991415-70e31680-6f8b-11eb-8cbd-0fcdeacf3f80.gif)
## Old
![mac_old](https://user-images.githubusercontent.com/18221058/107991414-6fb1e980-6f8b-11eb-9b21-fbc151502dc8.gif)

**Comment by coiko** [comment]
@KianBadie This looks great to me!  Thanks!  (And yes, I think it's fine to leave the white background for now.)

**Comment by KianBadie** [comment]
@coiko Here is what the initial implementation of the video quality switcher looks like! Is there anything you think it needs in terms of styling? The next thing I plan on adding is maintaining selected video quality across pages. Unfortunately, when this gets pushed to the main branch, it won't be possible to test with our current set up since the 480p videos live on the main site. Maybe their might be enough space on the staging site to host 1 video for testing purposes.

## Gif
![switch](https://user-images.githubusercontent.com/18221058/108573326-22a28000-72c9-11eb-91eb-300fdc976c2b.gif)
![switch2](https://user-images.githubusercontent.com/18221058/108573491-980e5080-72c9-11eb-8dbb-ba4d0a8e26fc.gif)

**Comment by coiko** [comment]
@KianBadie Oh that's cool!  And it would great to "remember" selections across pages.  Style-wise, if it's easy to change, I might just make it smaller (maybe 30% smaller so it's about the same size as the time indicator in the viewer) and have the selected radio indicator be grey instead of blue.  Otherwise, I think it's great.  Thanks!

**Comment by KianBadie** [comment]
@coiko The videos now "remember" the quality as you navigate pages. In addition, I applied the quality changing functionality to the modal videos. I figured a "change one change all" behavior made sense because I assumed if someone changed quality on one video, they would want that quality on the other videos as well (you can see the modal/section video changing simultaneously). Also, I tried to change the styling of the buttons to match your suggestions. How does it look to you? Do you think it could use more changes? 

## Gif
![test](https://user-images.githubusercontent.com/18221058/108910363-98b12a80-75da-11eb-9f1b-007770fadd9e.gif)
## Screenshots
![Screenshot from 2021-02-23 13-22-30](https://user-images.githubusercontent.com/18221058/108910348-93ec7680-75da-11eb-82be-f0daef3d65ed.png)
![Screenshot from 2021-02-23 13-22-37](https://user-images.githubusercontent.com/18221058/108910343-92bb4980-75da-11eb-8e26-044ca93b80ae.png)

**Comment by coiko** [comment]
@KianBadie This is fantastic!  I think it's perfect!

**Comment by KianBadie** [comment]
@coiko I was thinking of pausing videos when modals open/close. So like the section video would pause when the modal opens and vice versa. I figured that not only would this already be expected, but maybe it would also help with people with slow internet in  the scenario where someone is accidentally streaming multiple videos. Now they would only be streaming one max. Just giving a heads up just in case the current functionality was desired for any reason! But I can imagine that you already expected this to be a thing!

**Comment by KianBadie** [comment]
@coiko Also, here is how the quality selector will look on mobile. Please let me know if you think any changes need to be made!

## Screenshots
![Screenshot from 2021-02-23 18-59-07](https://user-images.githubusercontent.com/18221058/108941049-3cb1ca80-7609-11eb-95cf-4af0e13f7491.png)
![nobar_controls](https://user-images.githubusercontent.com/18221058/108940871-f492a800-7608-11eb-804c-f1ccf4d9830e.png)
![bar_controls](https://user-images.githubusercontent.com/18221058/108940870-f3fa1180-7608-11eb-85cd-2cb4d8b4db06.png)

**Comment by coiko** [comment]
@KianBadie Yes, I love the idea of having the videos pause when a modal is closed/opened!  (It was even on my wish list of things to ask you about someday.)

As for the quality selectors on mobile, I wonder if we should only serve 480p on mobile?  Given the size of the screen, 1080p is wasted and it might be a kindness to go a little lighter on data.  What do you think?

**Comment by KianBadie** [comment]
@coiko I think that is an interesting point. As of right now I would personally lean towards having both as options, but maybe making 480p the initial default setting if desired. With the current setup, I think if 1080p was an option, it would affect the data too much because the videos themselves wouldn't load until the quality button is switched. I also think it doesn't hurt to give options to the user for those who want it. On mobile, did the quality changer take away from the experience visually in any way? Or was this purely for data reasons?

**Comment by coiko** [comment]
Thanks @KianBadie!  My thought was that the size at which the wide-format 480p video is as high-quality as the 1080p video is larger than even a large phone.  So as far as I can tell, there's never a benefit to offering 1080p for true mobile layouts.  (And I can imagine myself saying "ooh!  1080p must be better.  Let me go with that" if I'm given the option.)  For a larger "mobile" layout like a tablet, of course, 1080p would be higher quality than 480p, so maybe we could think about adding another, intermediate, level to the screen size response. Anyway, maybe we should discuss this in person since I think I need a refresher on where you set the layout behavior switch. But that was my initial thought.

**Comment by KianBadie** [comment]
@coiko Ah I see what you are saying now. Admittedly, this was not something I was knowledgeable about. After spending some time researching, I am a bit unsure about which route to take now. It seems that there are a good amount of smart phones today that have resolutions high enough to support 1080p. But like you pointed out, there are also smart phones that look like they support 720p but not 1080p. The thing that I am wondering is even if a phone supports 1080p, is there a noticeable difference? 

I think I want to do some personal tests with the phones I have access to that support/don't support 1080p. It looks like your phone has a resolution of 2,960 x 1,440 pixels, so I think it will support the 1080p. If you had the time, would you mind viewing some of the cell videos in 480 vs the 1080? If you couldn't tell the difference on your phone, then I think that would be very telling in this decision. Please let me know if I misunderstood anything that you mentioned!

**Comment by KianBadie** [comment]
@coiko Also, are you satisfied with the scrubbing that Safari has? I am trying to wrap my head around how to possibly implement scrubbing, and I was wondering if Safari was the goal to try to achieve.

**Comment by coiko** [comment]
@KianBadie Sorry for the slow response!  I still haven't uploaded a 480p/1080p to view on my phone, but I'll let you know as soon as I try it.

In the meantime, yes, the scrubbing on Safari is great, so if you can figure out how to implement a viewer with similar capability on all browsers, that would be fantastic!

**Comment by KianBadie** [comment]
@coiko No worries, and thank you!

Sounds good, I will look further into that!

**Comment by coiko** [comment]
@KianBadie Sorry it took me a while, but I finally checked out the video resolution issue on my phone (Pixel 3XL).  With the videos taking up the full screen in landscape, the 1080p does look slightly higher-quality than the 480p, so I vote for including the option on mobile.  And then to answer your initial question, yes, the styling looks great!

**Comment by KianBadie** [comment]
@coiko no worries at all and that is great to hear! And sounds good, I will keep the styling!

**Comment by KianBadie** [comment]
@coiko Performing my own tests on my iPhone 8 (which has a 1334x750 pixel resolution), I did see a noticeable difference. My vote would also be to keep the 1080p. These screenshots were taken from my phone. It's interesting that the difference is more noticeable here when uploaded to this GitHub comment. It looks like the size of the screenshots got increased.

![IMG_3228](https://user-images.githubusercontent.com/18221058/109241078-8f1bf400-778d-11eb-8398-f5d081c36511.PNG)
![IMG_3229](https://user-images.githubusercontent.com/18221058/109241074-8d523080-778d-11eb-98f0-762a018d1f6c.PNG)

**Comment by coiko** [comment]
@KianBadie Awesome!  Thanks for checking it out.  This is very similar to what I saw, too.  So yes, let's keep 1080p as the default!

**Comment by KianBadie** [comment]
@coiko I have some progress to show with the custom video player and scrubber! As we talked about, the player is able to scrub through footage that has already played. As you can see, there are still visual bumps to work out and features to be implemented (implementing showing buffered time in the timeline, video download button).

In addition, there is some sort of bad news. As of right now I don't think this feature will be accessible in our testing branch. The method that I am using for scrubbing (painting frames to a hidden canvas) does not like it when the source of the painting is from a different origin. On the main site, the videos and the pages live under the "http://cellstructureatlas.org/..." url. However, the testing site has a different url from the videos. So the good news is that the feature can still be implemented, however it will be difficult to test. Things can be tested locally with some extra steps, however. So it is possible, but inconvenient if you wanted to test. I will look into other possibilities to test on our testing site.

## Gif
![test](https://user-images.githubusercontent.com/18221058/109723175-957de780-7b62-11eb-808e-c9a53ab033b7.gif)

**Comment by coiko** [comment]
@KianBadie Awesome!  This is looking great.

I don't think you need to add a video download feature (since that's available through the DOI in the video citation), but the buffer indicator would be cool.  And as for testing, don't worry too much about figuring out how to get it on the testing site.  I can definitely try it out on my local machine when the time comes.  We should just make sure that it still behaves well when the videos are being served over an internet connection before updating the main site.

**Comment by KianBadie** [comment]
@coiko All of that sounds good! I will keep you updated on the progress as it comes!

**Comment by KianBadie** [comment]
@coiko Here is a quick gif of my experiences with the scrubbing that I described in my most recent email! Did this gif properly cover the use cases we were describing or is it missing something? Were you having different experiences from what is shown here?

## Gif
![test](https://user-images.githubusercontent.com/18221058/110376353-ef215e80-8007-11eb-9a19-790c4ba9869d.gif)

**Comment by KianBadie** [comment]
@coiko I created some mocks of how the video quality selector could look like based on some other great examples I saw online. Do any of these look like a good fit, or at least in the right direction? What are your thoughts on implementing something in these styles?

One nice thing that could be added to these that are not reflected in the mocks is to highlight the currently hovered quality a lighter shade of grey when changing the quality.

- [Curved Extension](https://www.figma.com/proto/RlhplqT8SjzaeMa6hmgpWq/Quality-Selector?node-id=101%3A2&scaling=min-zoom&page-id=0%3A1)
- [Square Extension](https://www.figma.com/proto/RlhplqT8SjzaeMa6hmgpWq/Quality-Selector?node-id=102%3A226&scaling=min-zoom&page-id=102%3A225)
-  [Curved Pop Up](https://www.figma.com/proto/RlhplqT8SjzaeMa6hmgpWq/Quality-Selector?node-id=102%3A452&scaling=min-zoom&page-id=102%3A451)
- [Square Pop Up](https://www.figma.com/proto/RlhplqT8SjzaeMa6hmgpWq/Quality-Selector?node-id=102%3A147&scaling=min-zoom&page-id=102%3A146)

**Comment by coiko** [comment]
Thanks @KianBadie! These are fantastic!  I like the Curved Extension the best, especially with the checkmark to indicate the selection (the first of the first design).  I think it's just right.

**Comment by KianBadie** [comment]
@coiko Sounds great! I will go ahead and implement that then!

**Comment by KianBadie** [comment]
@coiko Currently, there is a bug where the modal text gets smaller and smaller when the screen becomes shorter. I attached an image of an example. At its extreme, the modal text does not show at all. 

One quick fix is to just make the text section always display in full, making the whole modal scrollable (shown in 2nd gif). However, as you can see in that gif, you lose the option to read the text while the video is playing. We could try to combine both options by having a minimum height for the text section (as in keep shrinking the text section, but not past a certain height), however at some point I think you would still be in same position as in the second gif after the text section reaches said minimum height. What are your thoughts?

## Example bug
![short_text](https://user-images.githubusercontent.com/18221058/114764636-0ba46b00-9d19-11eb-8850-569527600f04.PNG)
## Modal Always Scrollable
![modal_flex](https://user-images.githubusercontent.com/18221058/114764836-45757180-9d19-11eb-834d-5bc0abcfcce0.gif)

**Comment by coiko** [comment]
@KianBadie Sorry for the slow response - I had to give this some thought.  Initially, I like your idea of having the whole modal scrollable, but I do see the problem if someone wants to read the text while watching the video.  The other thought I had was that maybe you could keep a minimum aspect ratio for the modal, so if the browser window is shorter (even if it's still wide), the modal will be narrower.  It makes the video/image smaller, which of course isn't great, but I think this should be a pretty special case and the user should be able to realize that they can make it bigger by expanding the window down.  What do you think?

**Comment by KianBadie** [comment]
@coiko I think I see what your saying. So as the screen becomes shorter, the modal will shrink in width to compensate? And it would only do this after a certain threshold? This is different from  just shrinking in height, which is what happens on the current site. Did I understand that correctly?

If I did get that correctly, I would be happy to try it out and see how it turns out!

**Comment by coiko** [comment]
@KianBadie Yep, that's what I was thinking.  I don't know how it will work, but maybe it's worth testing?  Thanks!

**Comment by KianBadie** [comment]
@coiko The quality switcher is coming along alright so far. I attached a gif to show how it looks (please ignore the black horizontal bars on the video controls. I think that is a side effect of the screen recorder I am using). I would like to have this merged in tomorrow. So I am going to sit on it for a bit longer to reduce the chances of letting more bugs slip in.

The nice part about this too is that it got rid of the video/slider height differences (at least on desktop, since the mobile uses the old quality switcher). So now switching between the 2 has no jumping.

## Gif
![switcher](https://user-images.githubusercontent.com/18221058/114954168-cf533680-9e0e-11eb-946e-c6f2de00c1c9.gif)

**Comment by coiko** [comment]
@KianBadie Oh I love it!  It looks so good!

**Comment by KianBadie** [comment]
@coiko The quality changer update is now merged and available to use on the testing site! Please let me know if anything comes up with it.

**Comment by KianBadie** [comment]
@coiko Here is a stab at fixing the modal windows and keeping a constant aspect ratio when changing the height. Does this look like an alright fix to you? I think it turned out nicely. You will notice a "jump" when moving to the shorter screen. If the screen is already short, it will just display at the correct height w/o a jump.

## Gif
![modal_threshold_js](https://user-images.githubusercontent.com/18221058/115314219-9e824280-a129-11eb-924f-90be8f0af7c8.gif)

**Comment by coiko** [comment]
@KianBadie I think it's perfect!  Thank you so much!

**Comment by KianBadie** [comment]
@coiko When you say "on Safari, in modals, looks like video player is down slightly in viewer (white bar at top) - let me know if you want a screenshot of this", is the screenshot below what you were mentioning? Or is it something else not captured in the screenshot?

## Screenshot
![modal_white_bar](https://user-images.githubusercontent.com/18221058/115975045-5b9fe080-a516-11eb-9500-e64c6ef954ae.PNG)

**Comment by coiko** [comment]
@KianBadie Yes, I think that's it (here's another screenshot just in case - the grey cell shape on the right makes it easy to see).  Also, I noticed it in modals yesterday, but now I realize it's doing the same thing for me in the main sections windows, too.  

<img width="1280" alt="Screen Shot 2021-04-24 at 4 40 56 PM" src="https://user-images.githubusercontent.com/56415464/115975751-65c4dd80-a51c-11eb-99aa-f1b7722b6dda.png">

**Comment by KianBadie** [comment]
@coiko Huh interesting bug. I have not noticed that yet. The screenshot I showed was actually highlighting something else, the white bar was from the video itself I think. But your screenshot very much shows a problem. I will look into that!

**Comment by coiko** [comment]
Thanks @KianBadie!  (It might just be a weird Mac thing.)

**Comment by KianBadie** [comment]
@coiko Has the video player breaking after switching qualities a couple times still been a problem? I have been trying to replicate it, and unfortunately/fortunately have not been able to replicate it. If it is still an occurrence, would we possibly be able to have a zoom meeting sometime soon so that I can see/inspect some things that might lie outside what a gif could show?

**Comment by coiko** [comment]
@KianBadie Nope - I can't get it to do it now on either browser even with extensive switching, so whatever you did (or whatever happened in the background) worked!

**Comment by KianBadie** [comment]
@coiko That is strange but great to hear! Please let me know if you experience it again. Also, the slightly off modal videos should be fixed now on our testing site!

**Comment by coiko** [comment]
@KianBadie That's wonderful!  Thanks!

**Comment by KianBadie** [comment]
@coiko I just merged some changes for added keyboard functionality to play the video on space bar when nothing that uses space bar is selected. If something has focus that uses space bar, the video will not autoplay but instead do the original spacebar functionality for that thing. For example, is the text section is focused/highlighted, the video will not play because spacebar is used for scrolling (spacebar goes down and shift + spacebar goes up by default). Buttons are another thing on that list. There is a bug on safari where using spacebar to play/pause the video will play the Mac error noise, which I will revisit in the future. It's non existent on Mac chrome however.

I also added functionality to have up/down scroll the text material if nothing is focused that uses the up/down controls (like the seek bar or the slider). 

There's still more to smooth out, but I figured there was enough improved to merge and save the rest for a future revisit. Please let me know if you experience any new bugs relating to this that might have slipped past me!

**Comment by coiko** [comment]
@KianBadie Thanks!  That's fantastic!  The up/down scrolling by default for the text works great for me, but I can't seem to get the spacebar to play the video (even when nothing else has focus).  I tried it on Chrome and Safari (both Mac).

**Comment by KianBadie** [comment]
@coiko I was able to look into the removing the audio from the videos. Turns out there is an attribute to denote that a video is muted. On my iPhone, this allowed me to listen to music while the video was playing (unfortunately, I can't test this on android at this moment because I currently only have access to remote android phones from a service, so I don't have access to things like music).

There are some other notable side affects however. Because audio is muted, Chrome/Safari's media tab menus did not acknowledge the video. I included screenshots of what these menus look like. You are still able to play the video in "picture in picture" mode, but you have to right click the video itself and select that rather than through these menus. I'm not sure what the "auto play" options do yet, as I fiddled around with them and did not experience any changes. In addition, on desktop, the browser stops the video when you switch to a different tab. I assume it kept playing before because it assumed you were still listening to audio. On mobile, I did not check for other side effects because things play in full screen, so it seems like the only relevant thing would be audio (all other controls stayed the same). On iOS, once volume is adjusted, the music will then mute. I think this is because the browser still assumes the video has audio, but was just muted. It seemed the same for Android. I did not test with music, but I noticed that the phone acknowledged Chromes audio once I unmuted the video.

Adding this change was really just adding one attribute to the video. So it can be added/removed on a whim when needed. What are your thoughts?

## Safari Menu
![tab-menu-safari](https://user-images.githubusercontent.com/18221058/122971682-28c26f00-d344-11eb-9c0b-e00eb2de78cf.PNG)
## Chrome Menu
![menu-chrome](https://user-images.githubusercontent.com/18221058/122970116-59090e00-d342-11eb-8ead-37a3cd1d7eb7.png)

**Comment by KianBadie** [comment]
@coiko I investigated the broken spacebar-autoplay functionality, and it looked like things were still working for me. Would you please be able to describe more of the bug you experienced? There are certain scenarios where it won't work by design. For example, if the text section is focused spacebar will not autoplay but instead scroll the text since spacebar is used to scroll pages on keyboard. The same goes for buttons. Does that fall into the bug you were experiencing? There might be a chance too that whatever I might have broke might have been indirectly fixed.

**Comment by coiko** [comment]
Thanks @KianBadie!  There must be something strange with my machine then.  I have the same problem on both Chrome and Safari (even after a hard refresh).  It does work if I'm focused on the video, just not globally.  For instance, it doesn't work when I land fresh on a page so no sections are focused.  (And it used to work.)  Anyway, if it's working for you, I wouldn't worry about it.  It's probably just a local glitch that shouldn't affect users.  I'll let you know if anything changes (or if I hear of anyone else experiencing it), but for now I think we can safely ignore it.

**Comment by KianBadie** [comment]
@coiko That is strange stuff! This might be silly to ask, but I also wanted to double check that this is on our testing site, correct? I just checked our main site and thought I found the bug there (since the videos weren't auto playing) only to realize that we added that feature after our latest release.

But please let me know if you keep on experiencing the bug!

**Comment by coiko** [comment]
@KianBadie Ha yes, definitely good to ask!  It is on the testing site.  (I had a similar experience where I thought I'd see if it was working on the main site and then remembered it wasn't on there yet.)

**Comment by KianBadie** [comment]
@coiko That is strange indeed. I did one last check before signing off and it did happen to me on the introduction page! So hopefully I can use that to get more insight on this bug. I will be able to look into that next week.

**Comment by coiko** [comment]
@KianBadie That's funny.  Don't worry about it too much, but thanks for looking into it!

**Comment by KianBadie** [comment]
@coiko My apologies for the lag on this small no audio video issue. Unfortunately, I still don't have a conclusive answer other than what I have shared in our meeting last week. However, I did notice something strange on my iPhone. Playing the no audio video takes a couple of seconds to start actually playing the video while the videos with audio play instantaneously. I'm doing all of this testing locally on my own network, so it might not be the same behavior as the actual site. 

May I know what program/settings you used to export the videos without audio? I just want to check in the case that this is a common thing with certain settings, if my phone is acting weird, or if it is just random and a coincidence that the slow start is happening with the no audio videos.

**Comment by coiko** [comment]
@KianBadie Weird!  I exported both the audio/no-audio videos from Adobe AfterEffects through Adobe MediaEncoder.  The codec was the same (H.264) and the only difference was the preset.  For the audio version, I used YouTube HD 1080p.  For the no-audio version, I started from that preset and just unchecked the "audio" box.  I'll see if I can find anything about it online, but let me know if you have any thoughts.  Thanks!

**Comment by KianBadie** [comment]
@coiko Weird indeed! I don't know why that behavior would happen. I'll continue searching as well. I will also be testing on an actual android device soon and I will let you know what my experience is.

**Comment by KianBadie** [comment]
@coiko So I got to testing on that android device and did not notice any slow loading. One idea I have is that maybe we can give the no audio video to Tom and upload it to the main site server. That way I can rule out local server circumstances as the cause for any problems. This will allow me to better test on the other remote devices I use as well, since trying to stream the videos to those remote devices from my own computer have proven difficult to produce meaningful tests. The video won't even need to be accessible on any pages, I could just use the url. What are your thoughts?

**Comment by coiko** [comment]
@KianBadie That sounds like a great idea!  I haven't had any luck finding any information about it online, so it sure would be nice if it were just a local server issue (unlikely, I know).  Thanks!

**Comment by KianBadie** [comment]
@coiko I did not have much luck either, but I just sent the videos over to Tom! Hopefully if everything is normal when on the server, we can forget that this whole bump in the road happened.

**Comment by KianBadie** [comment]
@coiko So I did some more testing on different devices to see the nuances of having the no audio videos vs audio videos. The differences are pretty much what you would expect. Like I said before, having no audio videos on desktop removes the quick access menu that is preset across tabs. Another difference on desktop is that videos will pause on tab switching. For mobile, you are able to control the device volume without having the music paused on a no audio video. One small detail that is aside from what I just mentioned is that having a "muted" audio video (still has "audio" but is just preset to mute) allows you to control device volume without pausing music on android, but iOS will pause the music once volume is changed on the device.

Lastly, back to that loading issue I mentioned. It does feel a bit silly that something this simple is raising eyebrows, and my apologies that something this simple isn't as straightforward as it is supposed to be. I recorded a gif of my experience to reassure myself that I am not crazy. As you can see in the gifs below, there is noticeable delay when playing the no audio video when compared to the audio video. I had trouble finding anything online discussing possible problems. The gifs are similar to what I experienced on my phone, but from my brief testing with an iPhone 12 I saw that the delay was shorter than what was shown here. What are your thoughts?

One option is to replace a couple videos on the site and let them marinate in the wild for a bit to see if things turn out normal.

## Audio
![ios_audio](https://user-images.githubusercontent.com/18221058/124809492-0704e280-df15-11eb-8a78-82dfa29a6135.gif)
## No Audio
![ios_no_audio](https://user-images.githubusercontent.com/18221058/124809507-0a986980-df15-11eb-8288-f40fae8b80b3.gif)

**Comment by coiko** [comment]
@KianBadie Thanks so much for this!  It is such a funny bug, but definitely real, so don't worry about going crazy!  It seems like the no-audio videos offer advantages generally, so I like your idea of releasing a couple "into the wild" and seeing how they perform for different people on different devices before committing to a site-wide change.  Do you have a preference for which ones to do?

**Comment by KianBadie** [comment]
@coiko Sounds good! As far as preference on videos, I would say anything after chapter 2. I frequent chapters 1 and 2 during development, which might get in the way of checking the videos out due to the url switching issue. In addition, I think it would be good to select a couple of videos that have share a similar file size to other videos throughout the site. That way we can have a good comparison point to really investigate the issue I described above. For example, 4_1 and 4_3 both have videos that are around 84MB, so making one of the no audio will let us compare to the other. Making the videos no audio might make the file size smaller. It doesn't have to be exact, so within around 10MB of another video seems to be like a reasonable range to make comparisons for me. Of course, if the no audio video size was almost the same size as another video that would be ideal. But if that's not possible then no worries!

These videos would end up being live on the actual site as well. If you'd like, I could make it only show up on the testing site if that is preferred. It would not be a hassle to implement.

**Comment by coiko** [comment]
@KianBadie That sounds perfect!  (And yes, it's totally fine if they're live on the actual site.)  The no-audio does seem to decrease the file size (another reason it would be cool if they actually worked), so I'll play with it a bit and try to get you a couple good candidates, following these guidelines, in the next day or two.  Thanks!

**Comment by coiko** [comment]
@KianBadie I sent you a couple no-audio videos to test out in the wild - let me know if you don't get the download link.  They should both be close in size to the video on the previous page (4_2_NoAudio is 88.4 MB compared to 83.4 MB for 4_1, and 9_5_NoAudio is 81.6 MB compared to 81.1 MB for 9_4).  Let me know if anything else would be helpful.  Thanks!

**Comment by KianBadie** [comment]
@coiko Thank you! Just downloaded them and I will pass along to Tom shortly.

**Comment by KianBadie** [comment]
@coiko Just wanted to give you a heads up that Tom replaced the site videos with the no audio videos you gave! I will check things out soon and let you know if I see anything out of the ordinary.

**Comment by KianBadie** [comment]
@coiko Thug bug that makes the scrub "screen" the wrong size on full screen that I mentioned in my earlier email is fixed. If you notice anything strange, please let me know. As I was fixing this, it is becoming more and more apparent that the implementation video player is in need of organization (which I have been working on). I have been saving integrating the new player after it is complete/this upcoming update. But fixing this bug makes me wonder if I should try it now and see how it goes, since there are a couple other bugs associated with the video player.

One odd thing (that seemed to be a problem no matter how the player was organized) is that an odd green line would appear at the bottom of the scrub screen. You can only see this in full screen mode, since usually the bottom of the scrub screen would be covered by the controls container in non full screen. It seems to be something to do with the built in method used to draw the video frames to the scrub canvas, but I haven't been able to find a cause. If you notice it on your end, please let me know so I can see if it is just on my computer or not. It was a bit difficult to confirm on Mac on my end, due to the service I use to remotely test. It wouldn't appear when I used different videos which made it even more strange.

Also, just as a reminder, all of this is only in Chrome. Safari is still using all the same stuff as before.

**Comment by coiko** [comment]
Thanks @KianBadie!  It looks great to me now, and I can't reproduce the green line in Chrome on Mac (which I think is good news).  I only tested a couple videos though, so I'll keep an eye out as I go through more.

As for tackling the video player optimization, it's totally up to you.  I think it would be great if you want to do it now, but if you have plenty on your plate and would rather wait until post-update, that's completely fine, too.

**Comment by KianBadie** [comment]
@coiko Oh wow that's great! I should also add that you will only see the line if the screen width is too short for the video to reach the full height of the screen, which results in the video being centered vertically on the screen while stretching to the full width (this might be hard to tell because the background of the player is the same background as the videos). If that is what you experienced, then I am glad that the problem isn't everywhere!

Sounds good. If I have time, I will go ahead and integrate it and see how it works out. If it only needs a couple of extra steps to get it fully working in the site, then I will try to include it.

**Comment by coiko** [comment]
@KianBadie Sounds great - thanks!

As for the green line, it sounds like I won't be able to see it since my displays are the same aspect ratio or wider than the videos, so they always stretch to the bottom in fullscreen mode.  On the bright side, that's probably true for a lot of users as well?

**Comment by KianBadie** [comment]
@coiko Ah, yes that makes sense. It probably will be the more likely case. The reason why I would see more often is maybe because I had the dev tools open, which I keep on the right side of my screen and takes up width. The dev tools stay open in full screen. Yeah if it is not too major we can save it for work in the future.

**Comment by coiko** [comment]
@KianBadie Ah thanks!  I tried it with the dev tools open and I didn't see any suspicious lines, so it might not happen on Mac.  And yes, it sounds not too major at all.

**Comment by KianBadie** [comment]
@coiko Ah I see, maybe it might be the fault of the browser? Strange thing was when I tried different video sources that weren't ours, I didn't see suspicious lines. Either way, if it's not too major I will go ahead and set it down for now.

**Comment by KianBadie** [comment]
@coiko I investigated the video player changing sizes when the quality is changed. I did find a possible fix for this, but it looks like the possible fix is what was causing the old bug of the extra space on the top/bottom of the videos (I attached a screenshot below). Unfortunately, I think this is a result of some of the unwise decisions I made in the fundamental styling of the video player. I don't think I can figure out a timely fix for that before the update, my apologies. With that in mind, do you feel like any of the bugs are the lesser of the 2 evils? If you think having consistent sizing for the video is worth the extra spacing, then I can try to investigate if this fix doesn't introduce any other bugs and then merge it. I ask because in my testing I did notice that the change in video player sizes was a bit unexpected and noticeable in terms of user experience.

## Screenshot 
![Capture](https://user-images.githubusercontent.com/18221058/129460305-64095d53-918e-4699-8a93-2279e72284cc.PNG)

**Comment by coiko** [comment]
@KianBadie Thanks so much for looking into this!  I'd vote for leaving it with the size-change-on-switching rather than reintroducing the extra space.  I think most users will consistently view the default 1080p on desktop (and only switch quality once if they do switch), so let's leave it optimized for that and not have the extra work/worry of changing this before the update.  (But let me know if you think otherwise!)

**Comment by KianBadie** [comment]
@coiko No problem! And thankfully, after reading your comment I tried one more time to get something working and I just merged a fix that looked like it worked without introducing other bugs. It kept the 480p/1080p video sizes the same without introducing the white space. Please let me know if any problems persists or if any new ones got introduced that I did not catch!

**Comment by coiko** [comment]
@KianBadie Oh beautiful!  It looks great to me.  Thank you so much!

**Comment by KianBadie** [comment]
@coiko I was doing some testing of the video player in chrome and noticed some odd behavior with the scrubbing. I think odd behavior with the video player and scrubbing has been around for a while, but I wanted to check in and ask if you have experienced any odd behavior with the video scrubbing in chrome? If so, do you think it is a major bug that affects the overall user experience, or do you think it is minor enough to let be for this update?

An example that I have is that it seems that the scrubbing saves the wrong frame for a given time sometimes. It seems to happen when skipping around a video before the video has played the part that has been skipped to. Below I have attached a gif of a video at a given time, and showing what the scrub screen displays for that time. Have you experienced something similar to what I have described? Or is this the first time you are hearing something like this?

## Gif
![bug](https://user-images.githubusercontent.com/18221058/129614243-35e2dbe2-e9ed-4778-80ee-f872776541b3.gif)

**Comment by coiko** [comment]
@KianBadie Ah, interesting!  I have seen this bug before, but not for a while.  I used to get it (rarely, as I remember) when you had first implemented the scrubbing and I was playing around with it and sort of trying to get it to break.  Since then, as I've been watching the videos in a more civilized fashion, I haven't encountered it.  So, since I imagine our users to be a civilized bunch, I wouldn't worry about fixing it now, but just put it on the list to potentially circle back to later.  What do you think?

**Comment by KianBadie** [comment]
@coiko I think that sounds reasonable to me, and definitely frees up my hands to see what I else I can work on! We can save it for after the update.

**Comment by KianBadie** [comment]
@coiko I was testing things out on Firefox after you mentioned the bug Grant was experiencing. I found that on the newest version of Firefox (91), videos are not able to play. Not just on our site, but even if I open the video link (for example, "https://www.cellstructureatlas.org/videos/1_10_Bbacteriovorus.mp4") in the browser it will never play. On previous versions of Firefox, playing the video in the browser and site works. Just wanted to keep you in the loop in case you experience it because it gave me quite the surprise. It seems to be a browser bug though. as things work as intended on previous versions on Mac.

**Comment by coiko** [comment]
@KianBadie Oh how strange!  I'm glad you discovered it.  From the Analytics, it looks like Firefox is a distant third in terms of usage after Chrome and Safari, but hopefully they iron out that bug soon.  Thanks!

**Comment by KianBadie** [comment]
@coiko No problem!

**Comment by KianBadie** [comment]
@coiko I pushed one last fix to help with some of the bugginess with the video player scrubbing. It does change the behavior of the video player slightly though, so I wanted to give a heads up. When seeking the video, like seeking 0:45 from 0:20 for example, the video player would show the frame for 0:20 and then show 0:45 when it loaded. This caused some flashing with the scrubbing because the scrub screen would should the saved frame for 0:45, then flip back to 0:20, then flip back to 0:45 when it loaded. 

Instead, what happens now is that the scrub screen for 0:45 won't disappear until it is loaded. Even though it is subtle, it is still not the norm for videos players. On YouTube for example, the 0:20 frame will stay showing until 0:45 loads (which is opposite of ours). Even though it is different, I thought it was worth it for less bugginess and that we can find a better solution in the future. What are your thoughts? Would you prefer the old version?

**Comment by coiko** [comment]
Thanks @KianBadie!  The behavior looks much better to me now, so I think it's definitely a keeper!

**Comment by KianBadie** [comment]
@coiko Great, I am glad it worked out!
