### ISSUE TITLE
Add 9.10 subsection "Entry" to phylogenetic tree

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#40]
9.10 subsection "Entry" is the only subsection with a "/" in the species name. Issue to fix tree to recognize that.

**Comment by KianBadie** [comment]
@coiko I just pushed some changes to add that subsection to the phylogenetic tree. Please let me know if any future changes are needed to that!

**Comment by coiko** [comment]
@KianBadie It looks great!  Thanks so much!
