### ISSUE TITLE
Fix narration control cut off in modals

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#42]

**Comment by KianBadie** [comment]
@coiko I just pushed some changes to fix the narration controls in the modals. Please let me know if they still need some changes!

![narration](https://user-images.githubusercontent.com/18221058/153929075-2fc17572-80fb-4540-a155-088fbeff73a3.gif)

**Comment by coiko** [comment]
Thanks so much @KianBadie!  They look great!
