### ISSUE TITLE
Add description metadata to pages

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#45]
Add description metadata to all pages. This data will be used as description metadata in resulting html page.

**Comment by KianBadie** [comment]
@coiko I pushed some changes today that use the description values you provided in the source files. The only files left that need descriptions are the appendix pages and the index page! For now, those pages result in a blank description but everything still functions properly. So no rush on including those.

**Comment by coiko** [comment]
Thank you so much @KianBadie!  I didn't do the appendix pages because their .md files were blank (since they're compiled by your build script). Where should I add the descriptions for those and the index page?

**Comment by KianBadie** [comment]
@coiko Ah, yes that makes sense! Now that the author-content-changes branch is updated, the each appendix page has a .md file in the "appendix/" folder. The index page has a "index.md" file in the root directory.

**Comment by coiko** [comment]
Thanks @KianBadie!  I see them now, and just added the descriptions.  I'll push them back with the feature metadata, unless you'd like them sooner?  Just let me know.

**Comment by KianBadie** [comment]
Pushing them with the feature metadata is fine! Thank you
