### ISSUE TITLE
Add functionality to create feature index through markdown metadata

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#46]
Add functionality to generate feature index data programmatically instead of using current features.json file.

**Comment by KianBadie** [comment]
@coiko I started to work on this feature and a question came up. I noticed that the feature index entries were using hardcoded titles that differed from how we usually title things. For example, one entry in the index is "6.9 Archaella Patterns: Cone structure". However, the actual title field of that subsection is "Cone". So if we were to generate that text with the title fields, we would get "6.9 Archaella Patterns: Cone". This would be more consistent, but I wanted to make sure with you if that is ok. If we were to stick with the previous naming ("6.9 Archaella Patterns: Cone structure"), we might have to add a few extra steps to get that down. I think it will be doable, but using the existing title fields would create less variables to update.

**Comment by coiko** [comment]
@KianBadie Absolutely!  The longer titles are an artifact from before we shortened the modal titles to fit better in the buttons. I actually wished we could use the shorter (current) titles in the feature index but thought it would be too much of a pain.  So yes, if you can do that, it would be great.  Thanks!

**Comment by KianBadie** [comment]
@coiko I realize now why you said it might be faster if you added the metadata for the features. If you still had the time, would you be able to add the data? If not, I would be happy to still do it! It would probably just take longer since I would use the features.json file instead of the excel sheet. I now see the nuances to the excel sheet that you warned me about in email.

If you did have the time, the format is simple. You would just add a `features` variable to the source markdown files. The value would be a list of feature names. The feature names would be written exactly how they appear on the feature index page. For example, `6-9-archaella-patterns.md` would have `features: ["Archaella", "Archaellar cone", "Membrane (monoderm)", "Ribosomes", "Surface layer", "Unidentified structures"]` included in its metadata. I have pushed this to the "author-content-changes" branch to start off. Would you have the time to do that? If you were up for it, there would be no rush on this and could be done on your leisure.

**Comment by coiko** [comment]
@KianBadie Of course!  I'm very happy to do this.  I'll pull from the author-content-changes branch and add the feature metadata.  Just to double-check (apologies for a dumb question), should I include quotation marks around the feature names?

**Comment by KianBadie** [comment]
@coiko Great, thank you! No apology needed and not a dumb question at all! For now, I think it will be safe to add them. If they are unnecessary, I will just remove them later.

**Comment by coiko** [comment]
Perfect.  Thanks @KianBadie!

**Comment by coiko** [comment]
@KianBadie I just pushed the feature metadata to the author-content-changes (along with the description metadata for the index and appendix pages). Let me know if you need anything else (or if I messed anything up)!

In the course of adding the features to the metadata, I noticed that at some point we lost the last item in the feature index, which should be "Virus-associated pyramids".  Could you add it back on if you get a chance while you're working on this functionality?  Thank you!

**Comment by KianBadie** [comment]
@coiko I'm still tying up those loose ends for the feature index. There were some things I wanted to run by you that came up:
- It looks like "Invasion portal" is missing from 9.10. Is this itentional?
- I changed the feature "Unidentified" in spore-engulfment.md to be "Unidentified structures" because I assumed that was the intention. Is this correct?
- I also assumed "Membrane inner)" in holdfast.md was supposed to be "Membrane (inner)". Is this correct?

Also, if I merge things today, are you ok if a few of the feature index entries are incorrect over the weekend? I'm assuming since this was a big initial data dump, it's likely there are some incorrect entries we have missed. If you want things to be corrected as soon as we find them, I can merge the changes on Monday so we can be at the ready to fix whatever comes up.

**Comment by coiko** [comment]
Ah, these are all fantastic catches.  Thanks so much @KianBadie!  Yes, "Invasion portal" should be in 9.10. Do you mind adding it?  And yes, both my typos should have been exactly what you thought. Thank you for fixing them.

And finally, yes, I'm completely fine with a few errors in the feature index over the weekend. Just to clarify, this will be on the testing site, not the main site, right?  (In which case, I'm doubly completely fine.)  Thanks!

**Comment by KianBadie** [comment]
@coiko I don't mind at all! I will make sure to remove "Unidentified structures" from 9.10 as well. Also. when you wanted me to add back "Virus-associated pyramids", was it just for sections 10.8 and 10.9? Were there any other features you wanted me to modify? My apologies, I can't seem to remember if you mentioned any in our meeting.

Sounds good! Yeah, this will all be on the testing site. And just to clarify myself, while there might be errors, I was more so trying to warn about incorrect feature entries in the index. Just wanted to clarify and make sure since this is more of a content thing than functionality related!

**Comment by coiko** [comment]
Thanks @KianBadie!  And yes, I'm sure all errors will be as a result of my sloppy manual entries!

Speaking of which, I realize I was too hasty in sending my last comment. The correct link for "Invasion portal" is actually the modal of 9.10, bdellovibrio-bacteriovorus-entry.md. I had missed it when we were cleaning up the incorrect section/subsection links in the feature index before.  Sorry!  So can you leave "Unidentified structures" in 9.10 (and not add Invasion portal there), and add "Invasion portal" to bdellovibrio-bacteriovorus-entry.md? Thank you!

And yes, "Virus-associated pyramids" should only be in sections 10.8 and 10.9.

**Comment by KianBadie** [comment]
@coiko No worries! I think they are pretty hard to avoid when doing a big change like this.

No worries again! I'll move those 9.10 related features around.

**Comment by KianBadie** [comment]
@coiko I just pushed the feature index update to the test site! Please let me know if you notice anything that needs changing. If, somehow, something that needs changing immediately slipped by me I would be happy to fix it over the weekend. I also decided to save adding the species field to CLEM for next week. Until then, I hope you have a good weekend!

**Comment by coiko** [comment]
It looks great - thank you so much @KianBadie!  And yes, I like the species / species format showing up (it makes sense here vs. the phylogenetic tree where it's better just to show the first one).  Have a great weekend!

**Comment by KianBadie** [comment]
@coiko I just added the "species" field to CLEM as well as the features. It will soon show up in the feature index. A couple other side effects of this is CLEM's species entry will also show up in its video citation, in search data, and in the phylogenetic tree. I think that just about wraps up the feature index update. If you notice anything that needs changing, please feel free to let me know here!

**Comment by coiko** [comment]
Thanks @KianBadie! The feature index is looking great.  The only thing I wish we could carry over from the previous version is to have the entries in each section first alphabetized by species name and then arranged by section number. That way, all the examples from a given species will be together.  Would that be feasible/easy to implement with your new compilation method?  (If not, of course, no worries!)

**Comment by KianBadie** [comment]
Ah I see, we can do that and it will be straightforward to implement!

**Comment by coiko** [comment]
Wonderful - thanks @KianBadie!

**Comment by KianBadie** [comment]
@coiko I added the functionality to sort the feature index entries by species names! Please let me know if you notice anything else is needed.

**Comment by coiko** [comment]
It looks fantastic.  Thanks so much @KianBadie!
