### ISSUE TITLE
Make index page more responsive

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#47]
Read now button is cut off on certain screen dimensions. Make read now button appear above the fold on more dimensions.

**Comment by KianBadie** [comment]
@coiko I added that responsiveness to get the read now button above the fold more often. It seems that the read now button appears above the fold on most dimensions except for very short screens. I assumed at that level of shortness, it's ok for things to be cutoff. But if that was the scenario you were trying to fix or if there are still instances were it is cut off please let me know!

![index](https://user-images.githubusercontent.com/18221058/156830728-c9a105bc-dfcf-41d5-81e5-82c97906b8e9.gif)

**Comment by coiko** [comment]
Oh fantastic!  Thanks so much @KianBadie!  I think it looks perfect now.

**Comment by KianBadie** [comment]
@coiko Great!
