### ISSUE TITLE
New video player update

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#48]
Replace the current player with [videojs](https://videojs.com/) to improve accessibility and reliability.

**Comment by KianBadie** [comment]
@coiko I just merged the video player changes today. There are still a couple of more things to fix to get closer to an identical experience to the previous player. But I wanted to open this issue to have a place to make note of any fixes/changes that need to be done.

**Comment by coiko** [comment]
Thanks @KianBadie!  The broad strokes look great!
