### ISSUE TITLE
Begin quote/introduction page titles are identical

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#49]
Best practice is for page titles to be unique. Currently, the introduction page and opening quote page have the title "Introduction | Atlas of Bacterial and Archaeal Cell Structure".

**Comment by KianBadie** [comment]
@coiko It's best practice for page title to be unique. The begin quote/intro page have identical page titles because their "title" metadata is "Introduction" in the markdown files. Would you like one of these to be changed?

**Comment by coiko** [comment]
Thanks @KianBadie!  And yes, let's definitely change one.  I remember we used "begin" for the intro quote file name, so how about we use that for the metadata title as well?

**Comment by KianBadie** [comment]
@coiko I think that sounds perfect!

**Comment by coiko** [comment]
@KianBadie Sorry for not thinking this through earlier!  I forgot that that would change the big title on the chapter head page, which looks weird to me now.  So if you don't mind, could we change the intro quote page (begin.md) title back to "Introduction" and change the content page (introduction.md) title to "Intro"?

**Comment by KianBadie** [comment]
@coiko no worries! Wow, my apologies that completely slipped my mind as well. I will go ahead and change that.

**Comment by KianBadie** [comment]
@coiko Just changed it. Please let me know if any other changes are needed!

**Comment by coiko** [comment]
Thanks @KianBadie!  It looks great!
