### ISSUE TITLE
Phylogenetic tree keyboard accommodations

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#50]
@coiko One last thing I wanted to see if I could squeeze in is an attempt at some keyboard accommodations for the phylogenetic tree. The easiest/quickest thing I could think of was to add keyboard panning to the tree graphic (with the zoom buttons still being reachable by keyboards) and to add a non-graphic version of the tree in list form. The way things are, it seemed like adding functionality to have the pop ups be reachable by keyboard would take more time.

I would recommend adding these, especially the keyboard panning since it is really subtle. I know the list is a bigger addition, so I can leave the code on a separate branch to be possibly merged at a later time if you'd like.

## Panning
![pan](https://user-images.githubusercontent.com/18221058/166303727-6824bad2-3501-4380-97d8-42f6e30eeb96.gif)
## List
![list](https://user-images.githubusercontent.com/18221058/166303751-b05fc7dc-05a0-45ea-8bfe-55f607cadd38.gif)

**Comment by coiko** [comment]
@KianBadie Oh I love it!  This is awesome functionality!  (I've thought about the alphabetical species list before, since it can be frustrating to search for names on the tree.)  If you're up for adding it, it would be fantastic - thanks!

My only very minor styling request would be to have the species names appear in italics, if that's easy to do (no worries if it's not).

**Comment by KianBadie** [comment]
@coiko Great! In that case it will be added by the end of the day!

That would be very easy to do! One thing I also took a guess at was the name "Species List". If that a good name for the header, or should I change it?

**Comment by KianBadie** [comment]
@coiko I just merged the changes! Things looked ok at a glance to me, but I plan on checking more thoroughly soon. Please let me know if you notice anything that needs changing!

**Comment by coiko** [comment]
@KianBadie Oh I love it!  It looks fantastic!  And yes, "Species List" is perfect.  Thank you so much!
