### ISSUE TITLE
Phylogenetic Tree revamp

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#7]
Revamp of the phylogenetic tree to better display its contents. Revamp will change the display of the tree to not show all leaves by default, but will instead display branches and give the users options to expand branches to see leaves. Leaves will be able to have multiple sections/links associated to them, instead of just 1 in the current implementation.

[phyloT](https://phylot.biobyte.de/) is used to generate the tree data and [iTOL](https://itol.embl.de/) generated the visual representation of the tree data.

## Screenshot from site
![Screenshot from 2021-03-30 11-04-46](https://user-images.githubusercontent.com/18221058/113035167-cd6b5100-9147-11eb-92d5-db49df376edb.png)

**Comment by KianBadie** [comment]
@coiko I did some looking into phyloT and iTOL and I had some questions that came up when I was thinking about how we could revamp the phylogenetic tree:
1. Will each branch have its own name and be collapsed by default. It looks like some of the terminal nodes in our tree have up to 3-4 parent nodes. Will those parent nodes have names? And will you have to click through the parent nodes to reach a set of terminal nodes? 
2. Do we want to keep the same styling for the tree? As in the only thing that will be changing is the functionality of it? Do we still want to keep the purple/green theme?
3.  Is the data set for the tree going to be exactly the same? As in the only things we are adding are the styling/functionality of expanding branches and showing multiple links per species?

**Comment by KianBadie** [comment]
@coiko I just tried tested out what it would be like if we inserted link tags directly around the svg text elements instead of drawing extra rectangles. The results look just about the same. I tried recording some gifs that show when the link is highlighted between the different methods (when the cursor turns into a pointer finger). 

The most noteworthy thing that I found was the wrong link opening on very close links in both instances (shown in the 3rd gif of the "Wrapping text with <a> tag" section below and the third gif of the "Original" section below). Hopefully, that will be solved since there will be no more links attached to those text, but instead they will open a pop up of sorts with links from there. Maybe we could add some extra indicators to make clear which pop up was opened (like some text highlighting/underlining. Maybe even the species name is the header of the pop up). What do you think?

# Wrapping text with `<a>` tag
![aText](https://user-images.githubusercontent.com/18221058/113442455-efadda80-93a4-11eb-855e-c31ed2fa8ed7.gif)
![aText2](https://user-images.githubusercontent.com/18221058/113442460-f0df0780-93a4-11eb-9dc4-34d6a121e369.gif)
## In this gif, you'd think the link for "Pseudomonas aeruginosa" would open, but the link for "Pseudomonas flexibilis" did.
![aGlitch](https://user-images.githubusercontent.com/18221058/113442473-f6d4e880-93a4-11eb-8234-46dd6fc32522.gif)
# Original
![original](https://user-images.githubusercontent.com/18221058/113442482-fb999c80-93a4-11eb-9719-5719ab374b5c.gif)
![original2](https://user-images.githubusercontent.com/18221058/113442483-fc323300-93a4-11eb-8e72-7b3ddee40ef6.gif)
## In this gif, you'd think the link for "Pseudomonas flexibilis" would open, but the link for "Pseudomonas aeruginosa" did.
![originalGlitch](https://user-images.githubusercontent.com/18221058/113442484-fc323300-93a4-11eb-9fb2-33dbb529b0f4.gif)

**Comment by KianBadie** [comment]
@coiko Also, I did some searching on the iTOL site. I did not see anything yet that allowed you to export the svg with the extra pop up functionality (even though I did find out that svgs can have some functionality built into them on their own). I could do some more looking in the future, but for now would you be ok with the current plan for the svg (zoom/pan with our custom popups only)?

**Comment by coiko** [comment]
@KianBadie Absolutely!  Thank you so much for looking into this!  And it's great news that we can use the text tags directly.  Yes, the close links are problematic, but I really like your idea of highlighting/underlining and having the species name title in the popup link box.

**Comment by KianBadie** [comment]
@coiko Progress on the functionality of the pan/zooming of the phylogenetic tree is going good so far. I have also started brainstorming what the controls would look like for the tree viewer. I am currently implementing scroll zooming, but it seems that having controls for zooming features seems to be a common practice on features like these. The only good example I can think of right now is Google Maps, but I can't think of any others currently. What do you think about including these controls?

If you would like to check out some ideas, here is a link to view them: https://www.figma.com/proto/j8GTC0kAW6Vaeruzr3H4JU/Tree-Update?node-id=29%3A15&scaling=min-zoom&page-id=0%3A1.

**Comment by coiko** [comment]
@KianBadie These are fantastic!  I like option 5 the best.  Would it also have the hand grab function (pretty sure it's not called that) to drag around the zoomed view?  Anyway, I definitely think this is the best type of controls for this.  

(Just for fun, I saw this zoom hover cursor for the first time recently and thought it would be good to keep in mind for something for the site, although I don't think it's actually useful for our images/videos: [https://journals.iucr.org/m/issues/2021/02/00/pw5016/pw5016fig1.html](url))

**Comment by KianBadie** [comment]
@KianBadie option 5 it is! That option is the blue pill in the top right of the viewer right? And yes, I also plan on having the hand grab function. I'm not sure what the official name is either, but hand grabber works out with me!

And that is a neat feature from that site. While you said you don't think it has a use case with our images/videos, are there any other use cases you were thinking of for the site? Or was it something to keep in mind if we need a zoom function like that in the future?

**Comment by coiko** [comment]
Awesome @KianBadie!  And yes, that was the one with the blue pill.  (And for the zoom feature, no, I didn't have any use case in mind - I just thought it might be good to file away mentally in case we need it for something unforeseen in the future.)

**Comment by KianBadie** [comment]
@coiko I was trying out the new svg and I noticed that there is an opacity to the background colors. The first screenshot below highlights what I am talking about. I'm not sure if the opacity was intended, or if it was a accident from picking a nice color over a white background. By any chance, would the second screenshot resemble what you were looking at when creating the svg?

In the 3rd screenshot, you can see what the svg looks like with the colors from the second screenshot (while also showing some of the zoom/pan functionality). What are your thoughts on the colors?

## Screenshots
![as_is](https://user-images.githubusercontent.com/18221058/113916372-befae600-9794-11eb-91f6-20d5b20ea1a0.png)
![white_background](https://user-images.githubusercontent.com/18221058/113916400-c6ba8a80-9794-11eb-80fc-7371552cdbf1.png)
![test_fill_fix](https://user-images.githubusercontent.com/18221058/113916383-c15d4000-9794-11eb-8b25-2f675448ac14.gif)

**Comment by coiko** [comment]
@KianBadie Ha, yes, sorry about that!  I forgot that svg preserves a transparent background, so I was working with everything on a white background and thinking it would appear that way.  The colors in the third screenshot look perfect (as does the zooming/panning)!  Thanks for fixing that!

As an aside, I think it's funny that the fonts change (serif or sans serif) depending on the viewer/browser.  There are a lot of features I hadn't appreciated about svgs.

**Comment by KianBadie** [comment]
@coiko Sounds good! I will change those colors then. It's probably happened to me too which is why it was my first guess.

Ah I see, was the original font supposed to be sans serif? I poked around and found this font name in the svg file: "Arial-ItalicMT". Was that the intended font? I'm guessing that because that font isn't on my computer, the browser didn't know what to do and defaulted to serif font. We could force a serif as the fallback instead of the sans serif one.

**Comment by coiko** [comment]
@KianBadie That makes sense.  I noticed it with the Bacteria and Archaea labels on the original one on the main site, too - they're sans serif on Chrome and serif on Safari.  It's not a big deal, but it might be good to go with sans serif if that's easy to set.  I'm attaching the screenshot of what it looks like on my computer.  The Bacteria/Archaea/Eukaryotes labels are Myriad Pro Semibold, and everything else is Arial - bold for the grey labels and italic for the teal ones.  Would it be better if I switched them to a more standard web friendly font?  Any suggestions?
![Screen Shot 2021-04-07 at 1 51 24 PM](https://user-images.githubusercontent.com/56415464/113932947-dd6adc80-97a8-11eb-95c2-f53e477881f0.png)

**Comment by KianBadie** [comment]
@coiko setting the fonts are an easy thing to change and guaranteeing a web friendly font is also easy to change since you can provide fall back fonts. For example, setting the font to "Font 1, Font 2, sans serif" will first check if font 1 is available, then 2, and if both are not available it will use whatever sans serif font is available. I think the easiest option for know would be to choose a [web safe](https://www.w3schools.com/cssref/css_websafe_fonts.asp) font and I can look into including some more custom fonts. Like the icons, I'm not sure yet how licensing goes with custom fonts, as I've seen things like paid fonts.

Other than picking a web safe font, there's no editing you have to do in the svg. That is pretty easy to change on my end!

**Comment by coiko** [comment]
Perfect - thanks @KianBadie!  Let's just go with Arial (with various sizes/bold/italic) for everything since that should be safe.

**Comment by KianBadie** [comment]
@coiko I also have made some mocks for what the pop up menus could look like [here](https://www.figma.com/proto/j8GTC0kAW6Vaeruzr3H4JU/Tree-Update?node-id=50%3A3&scaling=min-zoom&page-id=50%3A2). They are pretty inspired by the [iTOL](https://itol.embl.de/itol.cgi) pop ups since they look very elegant, and I also tried to make them look similar to the modals. 

They look pretty simplistic, but I worry that they look a little bland. I'm having trouble squeezing out the creative juices right now on how to spice them up while not being overtly loud, but I wanted to make them available to see if you had any input!

**Comment by coiko** [comment]
@KianBadie I love it!  It's clean and elegant.  I like the version with the rounded corners the best.  My only suggestion would be to replace "Read More:" with "Examples:"  Otherwise I think it's perfect!

**Comment by KianBadie** [comment]
@coiko Sounds great! I will go ahead and go with the rounded corners and replace the "Read More:". Thank you!

**Comment by KianBadie** [comment]
@coiko The new updates the the phylogenetic tree are live on the site! You'll be able to zoom/pan the tree with pop up menus appearing when you hover over parts of the tree. You can zoom with the controls in the top right or with scrolling while the mouse is in the tree viewing box. As you use it, please feel free to let me know of any bugs or improvements.

Some improvements I can think of already are detecting how much screen space there is (right now, pop ups always appear above and to the right of the mouse even if their isn't much screen space) and adding keyboard controls (arrow keys panning and maybe +/- zooming while the tree is focused). Also, there is currently a bug in Safari where if you scroll down the page and the mouse lands in the tree viewer, the tree will zoom out (expected) but the bottom padding of the overall page will disappear. So just know that the padding is still intended to be there! 

## Gif
![test](https://user-images.githubusercontent.com/18221058/114253184-fe286300-995d-11eb-8567-0adce0579937.gif)

**Comment by coiko** [comment]
Wonderful!  Thank you so much @KianBadie!

**Comment by KianBadie** [comment]
@coiko I wanted to confirm a few more details about what we discussed our last meeting about having an "isolated" view of the phylogenetic tree on desktop. I remember we wanted a modal like view when in the isolated view. Do we want the tree to display over a white background? As in using the same exact frame as all other modal content uses? Or would you like the grey borders of the tree viewer to just take up as much space as a normal modal? As in the tree viewer element just expanding to take up more screen space? I'm also assuming the same answer to these questions would go for the comparison sliders on desktop as well.

Lastly, I just wanted to double check on the full screen for the tree in mobile. Do we want that to be the same full screen as the comparison sliders? Takes up whole page (hiding the header/footer) and having that black background?

**Comment by coiko** [comment]
Thanks for following up @KianBadie!  I think it might be distracting to change the background color of the tree, so it's probably better to keep the grey background and just expand it to take up as much space as a modal.  (And yes, I think the comparison sliders could also expand to the height of a normal modal.)

And yes, I think the fullscreen on mobile would work great exactly the same way as you did the comparison sliders!

**Comment by KianBadie** [comment]
@coiko Thank you for the quick follow up! Sounds good, I will try to implement it that way then. I just noticed I used the word "expand", and wanted to clarify (just in case) that it might be a little difficult initially to get a smooth expanding animation, which I feel like the term "expanding" implies. Having a quick jump between normal and isolated will be much easier to implement at first. When I mentioned "expand", did you have an smooth animation/transition in mind? If so, would you be ok with having this easier implementation as a first goal and see what we can do after that?

**Comment by coiko** [comment]
@KianBadie Of course - a one-jump transition will be perfect!

**Comment by KianBadie** [comment]
@coiko Here is how enlarging the tree viewer is looking so far. What are your thoughts on it? Would there be any changes you would recommend?

## Gif
![tree_enlarged](https://user-images.githubusercontent.com/18221058/115937521-03e97280-a44d-11eb-8237-3a9bafafcf91.gif)

**Comment by coiko** [comment]
@KianBadie That looks fantastic!  If it's easy to change, I might make the enlarged window even bigger, maxing out the available space above and below like you did for the modals.  What do you think?

**Comment by KianBadie** [comment]
@coiko Will do! Also, this feature is working well so far. I will merge it in later today so it should be available over the weekend!

**Comment by KianBadie** [comment]
@coiko There was an interesting case that I wanted to get a second opinion on. The smaller the screen gets, the less functional the enlarge feature becomes. As you can see in the gif below, the height of the phylogenetic tree stays the same, but the enlarged version is sized to fit nicely in the viewport. The result is the "enlarged" version is smaller than the normal version. The first gif shows a long but short situation. The second gif shows a tall but narrow situation.

Do you think these screen sizes should be treated as passable edge cases? Or do you think there should be some sort of different functionality (for example, a max height on the tree so that the it won't take up as much space in situations like the first gif)?  As of right now, it seems like a passable edge case, but I will keep it in mind and see if any new thoughts come up.

Also, the enlarged tree viewer is available on the testing site as well! Let me know if it still could take up more space or if any other issues came up with it.

## Gif
![tree_small](https://user-images.githubusercontent.com/18221058/115939646-9b51c400-a453-11eb-8a5f-5f3f068b7a72.gif)
![tree_small_2](https://user-images.githubusercontent.com/18221058/115939871-7a3da300-a454-11eb-8727-0bfcff5fe214.gif)

**Comment by coiko** [comment]
@KianBadie I just checked it out on the testing site and it looks awesome - thanks!  As for these unusual aspect ratios, I agree that they're probably edge cases and it's fine to leave it with the expanded view being similar in size or smaller than the in-page view.  I think it will give the user the prod to realize they can enlarge it by dragging out the browser window.

**Comment by KianBadie** [comment]
@coiko Glad it is turning out well! And sounds good, acceptable edge case it is until said otherwise!

**Comment by KianBadie** [comment]
@coiko For the background of the tree in mobile full screen, would you like the dark grey to just be the background of the tree viewing widget? Or would you like the whole page to be dark grey? As in the background of the tree widget is dark grey and the widget is on a page with a dark grey background (I think this description is pretty much for portrait orientation, when there is plenty of space above and below the widget)?

**Comment by coiko** [comment]
@KianBadie Yes, I think the dark grey is fine just as the widget background (with the page background black as usual).  Thanks!

**Comment by KianBadie** [comment]
@coiko I looked a bit into the line faintness on the phylogenetic tree on chrome. I'm not sure why Chrome ends up with thinner lines, but I ended up just redefining some of the style rules to get things working. I added some screenshots to show the results ("Current" means what is currently on our testing branch). I also think that Windows is using a serif font, but I can also redefine that rule to use a sans-serif font.

## Current Mac Safari
![tree_current](https://user-images.githubusercontent.com/18221058/116129661-38447500-a67f-11eb-90fa-e3613cc948f0.PNG)
## Fix Mac Safari
![tree_new](https://user-images.githubusercontent.com/18221058/116129690-3e3a5600-a67f-11eb-829e-14931d33e4a4.PNG)
## Current Mac Chrome
![tree_current_mac_chrome](https://user-images.githubusercontent.com/18221058/116129716-44c8cd80-a67f-11eb-868b-d6c6aff52cf1.PNG)
## Fix Mac Chrome
![tree_new_mac_chrome](https://user-images.githubusercontent.com/18221058/116129729-4b574500-a67f-11eb-8b1d-8a22711a8397.PNG)
## Windows Chrome
![tree_new_windows](https://user-images.githubusercontent.com/18221058/116129741-4f836280-a67f-11eb-8e1e-a908a7bcadd3.PNG)

**Comment by coiko** [comment]
@KianBadie Oh beautiful!  (And yes, it would be great to specify sans serif font for Windows if that's easy.)  Thanks so much!

**Comment by KianBadie** [comment]
@coiko The tree updates are live on our testing site! Please let me know if anything comes up with them.

**Comment by coiko** [comment]
@KianBadie Woohoo!  Thanks!  (And will do.)

**Comment by KianBadie** [comment]
@coiko I modified the new tree that you sent and tried to add some extra thickness to the lines to make them stand out. How do they look to you? The lines are a bit hard to make out until you zoom in to a certain degree. Which is why I uploaded images as well of how the viewer looks once you enlarge it.

## Chrome
![modified_tree](https://user-images.githubusercontent.com/18221058/116762492-728b7a80-a9cf-11eb-9107-378bef737dd1.gif)
## Safari
![modified_tree_mac](https://user-images.githubusercontent.com/18221058/116762501-78815b80-a9cf-11eb-9384-a4ba03296e46.gif)
## After enlarging Chrome
![initial_enlarge](https://user-images.githubusercontent.com/18221058/116762518-820ac380-a9cf-11eb-8fbd-c088087533b3.PNG)
## After enlarging Safari
![initial_enlarge_mac](https://user-images.githubusercontent.com/18221058/116762532-8d5def00-a9cf-11eb-9fa1-c49882f74f49.PNG)
## iOS Safari
![modified_tree_mobile](https://user-images.githubusercontent.com/18221058/116762546-951d9380-a9cf-11eb-8806-27766a882e1c.gif)
## Android Chrome
![modified_tree_mobile_android](https://user-images.githubusercontent.com/18221058/116762557-9a7ade00-a9cf-11eb-8eb9-bc9cba82272a.gif)

**Comment by coiko** [comment]
Oh perfect!  Thank you so much @KianBadie!

**Comment by KianBadie** [comment]
@coiko No problem! The changes are live on our testing site now.

**Comment by KianBadie** [comment]
@coiko I was going to get a little work in on some bug fixes for the phylogenetic tree. The first things was getting that broken link for the last example of "Caulobacter crescentus" to work. I believe the cause of the problem is the file name "φcb13-infection". The way I made things, the id's of the links are created from the file names. Because of that, I'm guessing phi for the url is different from the phi in the page (in particular, it looks like my browser url always uses the lower case phi, while the modal metadata in the page is using the upper case phi). While there are multiple ways to change the way I make the links (like detecting when this url comes up and generating a url with safer characters), I figured an easy way could be to rename the file. In the future, it could prevent some character dependent bugs in the script if we stick to strict a-z and 0-9 for the file names. 

Would that be inconvenient or take away any meaning from the file? I was thinking of a name like "PHIcb13-infection". What do you think? Renaming this shouldn't change the appearance of the rendered site, and if it did I could figure out a way to change the name and keep things looking the same. If you prefer to keep the name, there is always another work around I can do.

**Comment by coiko** [comment]
Thanks @KianBadie!  That sounds perfect.  As long as it shows up with the Greek letter phi on the site, there's no problem at all.

**Comment by KianBadie** [comment]
@coiko On the page itself, the phi will still remain a Greek letter, however the only visible part that will no longer have the Greek letter is the url (since the url will be https://.../10-6-head-fibers.html#<subsection id>). Is this still ok with you, or is it more desirable to have a different work-around? Either is fine with me!

**Comment by coiko** [comment]
@KianBadie that sounds perfect - thanks!

**Comment by KianBadie** [comment]
@coiko For auto enlarging the tree when accessed through a species link, there is a problem with doing that on mobile (at least on android). For security reasons, the browser doesn't allow things to go full screen without user interaction (like a button press). So trying to go full screen with the tree when the page loads will not work. One idea I had is to display a prompt like "Allow Phylogenetic Tree to enter fullscreen to view more examples of Bdellovibrio bacteriovorus?" The browser has the built in functionality to display prompts like this with simple ok/cancel options. However, it seems that prompts like those are not considered user interactions for some reason. So we would probably have to display our own "full screen?" prompt. What do you think?

**Comment by coiko** [comment]
@KianBadie I think that sounds like a fantastic solution!  If we want a shorter message (for mobile attention spans), we could also do something like "Allow Tree to display fullscreen?"

**Comment by KianBadie** [comment]
@coiko Awesome! And I think that message sounds good to me too!

**Comment by KianBadie** [comment]
@coiko In terms of styling, I was thinking of doing something like this:
![confirm](https://user-images.githubusercontent.com/18221058/122091677-e803ac80-cdbd-11eb-8751-4c295577103b.PNG)

But maybe with only one font type (no bold title/normal body) and our modal styling. The blue "cancel"/"ok" could be a shade of the dark blue we use a lot and adjusted if necessary for the white background.

**Comment by coiko** [comment]
@KianBadie That looks/sounds fantastic!  Thank you so much!

**Comment by KianBadie** [comment]
@coiko Adding these changes was a bit more confusing than it should have been, so I started to refactor/organize some of the code. While doing this, I realized that the protein viewer maintains a certain aspect ratio when in portrait fullscreen (about the same aspect ratio as comparison sliders). Since I was already at the point of rewriting this, I wanted to see if you wanted to take the opportunity to change it to be completely fullscreen like the protein viewer (that is, if you think it looks better). What are your thoughts? Should it stretch to be the full screen height on portrait fullscreen, or maintain an aspect ratio?

**Comment by coiko** [comment]
@KianBadie Ooh...I like the fullscreen option!  I had actually wondered about it before since it's nice to have that extra real estate in a zoomed-in view but I figured it wasn't worth the effort since the user can just flip the phone.  But if it's not hard to implement now, that would be fantastic.  Thanks!

**Comment by KianBadie** [comment]
@coiko Sounds good! Thankfully, with the reorganizing, it's actually easier to do it full screen than to try to keep an aspect ratio.

**Comment by KianBadie** [comment]
@coiko I just merged some updates for the tree, so they should be available very soon. This update added the auto opening feature and made the tree take up the whole screen on full screen. There are some quirks that were introduced when I reorganized things, but I felt like they were minor enough to come back to later. But, just to have everything out there I will list the notable quirks I ran into:
- Attempting to enlarging the tree with the nav menu opened will close the nav menu, make the page "jump" down, but the tree won't enlarge.
- If you open a species pop up using touch, pan or zoom the tree using touch, you will not be able to reopen that same menu until you click on another one and then back to that one.
- Auto opening pop up menus on android open a bit off. On desktop/ios, the menu opens as if your mouse is on the species entry (at least on the ones I tested). On android, it opens an inch or 2 off. I assume this is because I have to do some more fine tuning since the browser changes to actual full screen on android as opposed to just enlarging on other platforms.

I wanted to try to get the other tree enhancements/fixes in today, which is why I thought it would be ok to save these for later. Please feel free to let me know if any of them or anything I didn't list are higher priority!

One other thing that I encountered was accidently opening another species pop up when another is auto opening. So I would click a species link in a section and the browser would navigate to the tree. But because my mouse was near the center of the screen from clicking the link, there was a chance my mouse would land somewhere near a different link. That would result in the intended menu being closed pretty quickly. Because of that, maybe something to implement would be to wait for a couple seconds to turn on the manual close/opening functionality of the pop up menus. That way, the user could navigate to that page, see the auto opened menu and then use the normal functionality of the tree after a couple seconds. Let me know how your experience goes with this issue and if you have any other thoughts!

Last thing I will say is that I reorganized a lot of the tree code. The attempt was that there would be no experience differences (besides enhancements), but please let me know if you encounter anything major with your experience that I accidently changed and did not notice in my checks and I will be happy to fix that!

**Comment by coiko** [comment]
@KianBadie Thanks so much!  This all sounds great!  I like the idea of implementing a couple second delay after auto-opening before the manual popup functionality comes into play.  I look forward to playing with the enhanced tree over the next few days and I'll let you know if I notice any bugs.

**Comment by KianBadie** [comment]
@coiko Sounds good, I will go ahead and implement that when there's time! I also just merged the fixes for the 10.6 modal not opening auto opening after clicking the link in the species pop up for "Caulobacter crescentus". In addition, sections 9.9-9.11 should all auto open/show up in the species pop up for "Bdellovibrio bacteriovorus". All the other species entries/links to species examples should have stayed the same (I checked a couple of them), but if you notice anything off with anything related to the species please let me know!

**Comment by coiko** [comment]
Awesome!  Thank you so much @KianBadie!  It looks great!  To be extra greedy (and sorry for missing this before), when you get a chance (no rush!), could you add one more example for Bdellovibrio bacteriovorus that's in a modal? It's 9.10:Entry.

**Comment by KianBadie** [comment]
@coiko Got 9.10:Entry into the tree and things are linked up properly! Please let me know if you run into anything else with the tree!

**Comment by coiko** [comment]
@KianBadie Awesome - thank you so much!
