### ISSUE TITLE
Landing Page Fixes

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#8]
Issue to discuss bug fixes/improvements on the landing page.

**Comment by KianBadie** [comment]
@coiko This was the solution I came up with for the landing page. The font decreases twice at fixed breakpoints and eventually becomes scrollable. What do you think? The only problem I could see is Macs hidden default scrollbars preventing people from seeing the Read Now button on very narrow screens. But I am wondering if that is a very small use case. The alternative is to keep the font proportional with the height at a certain point.

## Gif
![landing_fix](https://user-images.githubusercontent.com/18221058/116010664-3aea9000-a5d5-11eb-9436-a75f4e7880c2.gif)

**Comment by coiko** [comment]
Thanks @KianBadie!  I think the first example (2 breakpoints and then a scroll) is perfect!

The boldness looks great, too!  I think we could maybe bump the font up a bit more in size, too, to make it almost as tall as the icon and absolutely irresistible to click.

**Comment by KianBadie** [comment]
@coiko How does this font increase look? Or were you thinking even more? I also added a second image where I made the font even bolder. I wasn't sure if it needed it when the font increased.

## Screenshots
![landing](https://user-images.githubusercontent.com/18221058/116141136-223db100-a68d-11eb-86fd-bcc10ea5a475.PNG)
![landing_bold](https://user-images.githubusercontent.com/18221058/116141141-24a00b00-a68d-11eb-8331-f830dcefc0c9.PNG)

**Comment by KianBadie** [comment]
@coiko After staring at the words at well for a little too long, I saw that you were right! Things will be merged into the site shortly with everything nice and centered!

**Comment by coiko** [comment]
@KianBadie Beautiful - I see it already!  Thanks!

**Comment by KianBadie** [comment]
@coiko I forgot to add the bolded/bigger font button to mobile. Here is how they look just so you have a heads up! The button is the same height but longer now. Do you want to keep the bolding on mobile?


## Gifs
![landing_bold_android](https://user-images.githubusercontent.com/18221058/116627747-903ede00-a902-11eb-85d8-6ff050e35ff3.gif)
![landing_bold_iphone](https://user-images.githubusercontent.com/18221058/116627753-9339ce80-a902-11eb-841b-439e8621df98.gif)

**Comment by coiko** [comment]
@KianBadie Thanks for adding this!  I like it!

**Comment by KianBadie** [comment]
@coiko Here is my initial take at the preview banner. The styling of the inside of the banner can be changed, but I attached some screenshots/gifs below to give an idea of how it changes the spacing. On desktop, the change is minimal. Mobile was a bit trickier because of the way I laid things out. 

Basically, the page is no scrollable on portrait (it used to be fixed). Also, as you can see, the iPhone 8 landing happens to have the read no button lined up with the bottom nav bar. While this happens to be a coincidence in screen size, it does point out that some space can be saved by reducing the original space between the title and the title banner. Lastly, you might notice that the android version has empty space at the bottom of the screen that is scrollable. Ideally, I suppose everything would be moved down and there would be less empty space, however, allowing things to be scrollable on shorter screens made this side affect necessary. There might be a better way to implement it, but because of the way I wrote things long ago, this seems like the best I can do at this time before the update.

What are your thoughts?

## Desktop
![landing-desktop](https://user-images.githubusercontent.com/18221058/130288275-2ab116d0-24de-414c-94e3-156b4d4b715d.PNG)
## Mobile
![landing-iphone8](https://user-images.githubusercontent.com/18221058/130288283-8d6a300e-dce5-4170-9a01-d62a2b6cbeef.gif)
![landing-pixel3](https://user-images.githubusercontent.com/18221058/130288285-f190b63c-8fde-486f-a810-a702f521e6c4.gif)

**Comment by coiko** [comment]
@KianBadie I think this looks fantastic - thanks!  Also, if it would improve the mobile experience to have the message on a single line (so it takes up less real estate), it looks like we could do that by dropping a couple words, e.g. "Edition 2.0 coming September 6th! Preview **here**"  (Or that might just make more scrollable space at the bottom?)  What do you think?

**Comment by KianBadie** [comment]
@coiko Sounds good! I think it would be worth to try and if we don't like how it looks we could always sneak the old phrasing back in there! How does that sounds? If you did want to change the phrasing, would you also want to change the spacing between the title and the title banner on mobile?

**Comment by coiko** [comment]
@KianBadie It's totally up to you!  I'm fine with it as it is now.  Also, if it's easier to just leave the banner as is, that's great, too.  (It's a temporary element, so definitely not worth adding work for.)  Thanks!

**Comment by KianBadie** [comment]
@coiko Sounds good! I will go ahead and just merge things the way they are for now since it is the end of my day and on Monday or this weekend I will tweak anything necessary!

**Comment by coiko** [comment]
@KianBadie Sounds great!  Have a wonderful weekend!

**Comment by KianBadie** [comment]
@coiko Just a heads up that you won't be seeing the preview banner on the landing page on the testing site for a bit. Because the landing page with the banner is only for the main site and not the "preview" directory, I am just creating a offshoot "index-temp" page with the banner that Tom can manually make as a the landing page for the main site.

**Comment by coiko** [comment]
@KianBadie Sounds great - thanks!
