### ISSUE TITLE
Chapter page fixes

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#9]
Issue to discuss bug fixes/improvements on the chapter page.

**Comment by KianBadie** [comment]
@coiko I bumped down the font size slightly just a notch. Were you thinking more or does this look good? Also, I increased the layout change breakpoint up a notch as well. Do you think it should be at a greater? I included screenshots of the intro and chapter 9 page right at their breakpoints (right before they stack on each other).

# Font Size
## Current
![chapter_current](https://user-images.githubusercontent.com/18221058/115972937-55096d00-a506-11eb-8a01-7f124fe349e6.PNG)
## Decrease
![chapter_decrease](https://user-images.githubusercontent.com/18221058/115972942-5f2b6b80-a506-11eb-8c2f-8f18d36adf16.PNG)

# Breakpoint
## Current
![chapter_width_original](https://user-images.githubusercontent.com/18221058/115972945-6b172d80-a506-11eb-8d14-2271046ba5eb.gif)
## Increase
![chapter_width_fix](https://user-images.githubusercontent.com/18221058/115972949-710d0e80-a506-11eb-9c72-efc14965a552.gif)

# Introduction page right at break point
![intro_break_new](https://user-images.githubusercontent.com/18221058/115972967-8f730a00-a506-11eb-97b2-250ccd58663e.PNG)
# Chapter 9 page right at break point
![chapter_9_breakpoint](https://user-images.githubusercontent.com/18221058/115973043-0e684280-a507-11eb-8cf3-9b503c180352.PNG)

**Comment by coiko** [comment]
@KianBadie It's perfect!  I think the break point is just right now.  Thanks!
